<template>
  <div class="request-editor">
    <nav class="request-tabs" aria-label="请求区域"><button v-for="item in sections" :key="item.key" :class="{active: section === item.key}" @click="section = item.key">{{ item.label }}<span v-if="item.key !== 'raw'">{{ count(item.key) }}</span></button></nav>
    <div v-if="suggestions.length" class="association"><PhLink /><span>发现 {{ suggestions.length }} 项可关联变量</span><button @click="$emit('suggest', suggestions[0])">关联 {{ suggestions[0].parameter }}</button></div>
    <template v-if="section === 'headers' || section === 'params' || section === 'data'">
      <div class="parameter-table">
        <div class="parameter-row table-heading"><PhCheckSquare weight="fill"/><span>参数名</span><span>参数值</span><span>来源</span><span>操作</span></div>
        <div v-for="row in rows" :key="row.name" class="parameter-row"><PhCheckSquare weight="fill"/><input :value="row.name" :readonly="hasDefault(row.name)" :title="hasDefault(row.name) ? '接口默认参数名不可重命名，可覆盖参数值' : '参数名'" aria-label="参数名" @change="rename(row.name, ($event.target as HTMLInputElement).value)"/><div class="value-field" :class="{ sensitive: isSensitive(row.name) }"><input :type="isSensitive(row.name) && !isRevealed(row.name) ? 'password' : 'text'" :value="display(row.value)" autocomplete="off" aria-label="参数值" @focus="focusedKey = row.name" @change="update(row.name, ($event.target as HTMLInputElement).value)"/><button v-if="isSensitive(row.name)" type="button" class="reveal-button" :title="isRevealed(row.name) ? '隐藏具体信息' : '查看具体信息'" :aria-label="isRevealed(row.name) ? `隐藏 ${row.name}` : `查看 ${row.name}`" @mousedown.prevent @click="toggleReveal(row.name)"><PhEyeSlash v-if="isRevealed(row.name)"/><PhEye v-else/></button></div><span class="source" :class="{overridden: row.overridden}">{{ row.overridden ? '场景配置' : '接口默认' }}</span><button class="icon-button" :title="row.overridden ? '移除覆盖，恢复接口默认值' : '接口默认参数，可编辑参数值'" :disabled="!row.overridden" @click="remove(row.name)"><PhArrowCounterClockwise /></button></div>
        <div class="parameter-row add-row"><PhPlus/><input v-model="newKey" placeholder="添加参数" aria-label="新增参数名" @keydown.enter="add"/><div class="value-field" :class="{ sensitive: isSensitive(newKey) }"><input v-model="newValue" :type="isSensitive(newKey) && !newValueRevealed ? 'password' : 'text'" placeholder="参数值" aria-label="新增参数值" @focus="focusedKey = null" @keydown.enter="add"/><button v-if="isSensitive(newKey)" type="button" class="reveal-button" :title="newValueRevealed ? '隐藏具体信息' : '查看具体信息'" :aria-label="newValueRevealed ? '隐藏新增参数值' : '查看新增参数值'" @mousedown.prevent @click="newValueRevealed = !newValueRevealed"><PhEyeSlash v-if="newValueRevealed"/><PhEye v-else/></button></div><span></span><button class="icon-button" title="添加参数" :disabled="!newKey.trim()" @click="add"><PhPlus/></button></div>
      </div>
    </template>
    <template v-else-if="section === 'json' || section === 'raw'">
      <div class="json-toolbar"><span>{{ section === 'json' ? 'JSON 请求体' : '完整参数覆盖' }}</span><button @click="format"><PhCode/> 格式化</button></div>
      <div class="code-editor"><pre>{{ lines }}</pre><textarea ref="textarea" v-model="text" spellcheck="false" aria-label="请求 JSON" @blur="commitJson" /></div><p v-if="error" class="error">{{ error }}</p>
    </template>
    <template v-else><div class="file-row" v-for="(files, key) in endpoint?.files || {}" :key="key"><PhFile/><strong>{{ key }}</strong><span>{{ (files as any[]).map(file => file.name).join('、') }}</span></div><n-empty v-if="!count('files')" size="small" description="接口未配置文件"/><p class="file-hint">文件沿用接口管理中保存的配置。</p></template>
  </div>
</template>
<script setup lang="ts">
import { computed, ref, watch } from 'vue';
import { PhArrowCounterClockwise, PhCheckSquare, PhCode, PhEye, PhEyeSlash, PhFile, PhLink, PhPlus } from '@phosphor-icons/vue';
const props = defineProps<{ modelValue: string; endpoint: any; suggestions: any[] }>();
const emit = defineEmits(['update:modelValue', 'save', 'suggest']);
const section = ref('headers'); const newKey = ref(''); const newValue = ref(''); const newValueRevealed = ref(false); const revealedKeys = ref(new Set<string>()); const focusedKey = ref<string|null>(null); const text = ref(''); const error = ref(''); const textarea = ref<HTMLTextAreaElement>();
const sections = computed(() => [{key:'headers', label:'Headers'}, {key:'params',label:'Params'}, {key:props.endpoint?.body_type === 'json' ? 'json' : 'data',label:'Body'}, {key:'files',label:'文件'}, {key:'raw',label:'JSON 覆盖'}]);
const fields = ['headers','params','data','json'];
const hasDefault = (key: string) => Object.prototype.hasOwnProperty.call(props.endpoint?.[section.value] || {}, key);
const isSensitive = (key: string) => /authorization|token|secret|password|passwd|cookie|credential|private[_-]?key|api[_-]?key/i.test(key);
const revealKey = (key: string) => `${section.value}:${key}`;
const isRevealed = (key: string) => revealedKeys.value.has(revealKey(key));
function toggleReveal(key: string) { const target = revealKey(key); const next = new Set(revealedKeys.value); if (next.has(target)) next.delete(target); else next.add(target); revealedKeys.value = next; }
const parse = (value: string) => JSON.parse((value || '{}').replace(/(:\s*)(\$\{[^{}\r\n]+\}|\{\{[^{}\r\n]+\}\})(?=\s*[,}\]])/g, (_, prefix, variable) => prefix + JSON.stringify(variable)));
const primary = computed(() => ['params','data','json'].find(field => Object.keys(props.endpoint?.[field] || {}).length) || (props.endpoint?.method?.toUpperCase() === 'GET' ? 'params' : 'json'));
const override = computed(() => { try { const value = parse(props.modelValue); return fields.some(key => key in value) ? value : {[primary.value]:value}; } catch { return {}; } });
const effective = (key: string) => key === 'files' ? (props.endpoint?.files || {}) : ({...(props.endpoint?.[key] || {}), ...(override.value[key] || {})});
const count = (key: string) => Object.keys(effective(key)).length;
const display = (value: any) => typeof value === 'string' ? value : JSON.stringify(value);
const rows = computed(() => Object.entries(effective(section.value)).map(([name,value]) => ({name,value,overridden:Object.prototype.hasOwnProperty.call(override.value[section.value] || {}, name)})));
const lines = computed(() => Array.from({length: Math.max(8,text.value.split('\n').length)},(_,i)=>i+1).join('\n'));
function publish(value: any) { emit('update:modelValue', JSON.stringify(value, null, 2)); emit('save'); }
function update(key: string, value: string) { publish({...override.value, [section.value]:{...(override.value[section.value] || {}), [key]:value}}); }
function remove(key: string) { const data = {...(override.value[section.value] || {})}; delete data[key]; publish({...override.value,[section.value]:data}); const next = new Set(revealedKeys.value); next.delete(revealKey(key)); revealedKeys.value = next; }
function rename(key: string, value: string) { if (!value.trim() || key === value) return; const name = value.trim(); const oldRevealKey = revealKey(key); const data = {...(override.value[section.value] || {})}; data[name] = effective(section.value)[key]; delete data[key]; publish({...override.value,[section.value]:data}); if (revealedKeys.value.has(oldRevealKey)) { const next = new Set(revealedKeys.value); next.delete(oldRevealKey); next.add(revealKey(name)); revealedKeys.value = next; } }
function add() { if (!newKey.value.trim()) return; update(newKey.value.trim(),newValue.value); newKey.value = ''; newValue.value = ''; newValueRevealed.value = false; }
function commitJson() { if (!['json','raw'].includes(section.value)) return; try { const value = parse(text.value); if (!value || typeof value !== 'object' || Array.isArray(value)) throw Error('请填写 JSON 对象'); error.value = ''; publish(section.value === 'raw' ? value : {...override.value,json:value}); } catch(e: any) {error.value = e.message || '请填写合法 JSON';} }
function format() { try { text.value = JSON.stringify(parse(text.value),null,2); error.value = ''; } catch {error.value = '请填写合法 JSON';} }
function insertVariable(reference: string) { if (section.value === 'raw' || section.value === 'json') {const el=textarea.value; const start=el?.selectionStart ?? text.value.length; const end=el?.selectionEnd ?? start; text.value=text.value.slice(0,start)+reference+text.value.slice(end); el?.focus(); return;} if (focusedKey.value) update(focusedKey.value,display(effective(section.value)[focusedKey.value] ?? '')+reference); else newValue.value += reference; }
watch([() => props.modelValue,section], () => {text.value=section.value === 'raw' ? props.modelValue : JSON.stringify(effective('json'),null,2);error.value='';},{immediate:true});
defineExpose({insertVariable});
</script>
<style scoped>
.request-tabs{display:flex;gap:18px;border-bottom:1px solid #e3e9ef;overflow-x:auto;margin-bottom:12px}.request-tabs button{flex:none;display:flex;align-items:center;gap:7px;padding:9px 2px;background:none;border:0;border-bottom:2px solid transparent;color:#78869b;font-size:13px;cursor:pointer}.request-tabs button.active{color:#008993;border-color:#008993}.request-tabs span{font-size:11px;border-radius:12px;background:#f1f5f8;padding:0 5px}.association{display:flex;align-items:center;gap:8px;padding:10px 12px;background:#e9f6f8;color:#00818c;font-size:12px;margin-bottom:12px;border:1px solid #ccebf0;border-radius:4px}.association button{margin-left:auto;color:inherit;border:0;background:none;cursor:pointer}.parameter-table{border:1px solid #e2e8ef;border-radius:4px;overflow:hidden}.parameter-row{display:grid;grid-template-columns:26px minmax(85px,1fr) minmax(100px,1.5fr) 80px 34px;align-items:center;gap:8px;padding:8px 10px;min-height:40px;border-bottom:1px solid #e8edf2}.parameter-row:last-child{border:0}.parameter-row>svg{color:#008e97;font-size:18px}.table-heading{background:#f6f8fa;color:#6e7e91;font-size:12px}.parameter-row input{width:100%;min-width:0;border:1px solid transparent;background:transparent;padding:4px 3px;font-size:13px;color:#233448;border-radius:3px}.parameter-row input:focus{outline:none;border-color:#008d96}.source{font-size:11px;color:#788b9f}.source.overridden{color:#2671ad;background:#edf6ff;padding:3px 5px;border-radius:3px;width:max-content}.icon-button{border:0;background:none;color:#6c8194;cursor:pointer;display:inline-flex;justify-content:center;align-items:center;width:28px;height:28px}.icon-button:disabled{opacity:.3;cursor:default}.add-row input::placeholder{color:#a8b5c5}.json-toolbar{display:flex;align-items:center;justify-content:space-between;color:#66778a;font-size:12px;margin:10px 0}.json-toolbar button{display:flex;gap:5px;align-items:center;border:1px solid #dae3ea;background:white;padding:4px 8px;border-radius:4px;color:#3b5266;cursor:pointer}.code-editor{display:flex;background:#202e3a;border-radius:5px;padding:12px;min-height:190px;max-height:300px;overflow:auto}.code-editor pre{margin:0;color:#8495a5;font:12px/23px monospace;padding-right:14px;user-select:none}.code-editor textarea{width:100%;resize:vertical;min-height:185px;border:0;outline:0;background:none;color:#bde6f0;font:13px/23px monospace;tab-size:2}.error{color:#d84141;font-size:12px}.file-row{display:flex;gap:12px;padding:12px;border-bottom:1px solid #e3e9ee}.file-hint{font-size:12px;color:#8191a1;padding:12px 0}.request-editor :deep(.n-empty){padding:25px}
.value-field{position:relative;min-width:0}.value-field input{display:block}.value-field.sensitive input{padding-right:32px}.reveal-button{position:absolute;top:50%;right:2px;display:grid;width:28px;height:28px;padding:0;transform:translateY(-50%);place-items:center;border:0;border-radius:4px;color:#6c8194;background:transparent;cursor:pointer}.reveal-button:hover{color:#008b95;background:rgba(0,139,149,.1)}.reveal-button svg{width:17px;height:17px}
</style>
<style scoped>
.parameter-table{max-height:220px;overflow:auto;scrollbar-gutter:stable}
.table-heading{position:sticky;top:0;z-index:1}
.parameter-row input[readonly]{cursor:default}
</style>
