<template>
  <section class="result-panel" :class="{fullscreen}">
    <header><nav><button :class="{active: mode === 'result'}" @click="mode = 'result'">运行结果</button><button :class="{active: mode === 'logs'}" @click="mode = 'logs'">执行日志</button></nav><span class="recent">{{ finishedAt ? `最近运行 ${finishedAt}` : '尚未运行' }}</span><button class="icon-button" :aria-label="fullscreen ? '退出全屏' : '全屏查看结果'" @click="fullscreen = !fullscreen"><PhArrowsIn v-if="fullscreen"/><PhArrowsOut v-else/></button></header>
    <template v-if="mode === 'result'">
      <div class="result-status" v-if="result"><span class="status-badge" :class="{failed:result.passed === false,skipped:result.skipped}"><PhCheckCircle v-if="result.passed" weight="fill"/><PhXCircle v-else-if="result.passed === false" weight="fill"/>{{ result.skipped ? '已跳过' : result.passed ? '通过' : '失败' }}</span><span>HTTP {{ result.status_code || '—' }}</span><span>{{ result.duration_ms ?? '—' }} ms</span><span>断言 {{ passedAssertions }}/{{ result.assertions?.length || 0 }}</span></div>
      <nav class="response-tabs"><button v-for="item in tabs" :key="item.key" :class="{active: tab === item.key}" @click="tab = item.key">{{ item.label }}<small v-if="item.count !== undefined">{{ item.count }}</small></button><button class="icon-button copy" aria-label="复制结果" @click="copy"><PhCopy/></button></nav>
      <details v-if="result?.data_driven_results?.length || result?.attempts?.length" class="execution-details"><summary>数据驱动与重试详情</summary><pre>{{ JSON.stringify({ data_driven_results: result.data_driven_results, attempts: result.attempts }, null, 2) }}</pre></details>
      <div v-if="running" class="pending"><n-spin size="small"/><span>步骤执行中，响应完成后展示结果</span></div>
      <div v-else-if="!result" class="pending"><PhPlayCircle/><span>运行场景或调试此步，查看响应与断言结果</span></div>
      <template v-else><p v-if="result.errors?.length || result.skip_reason" class="errors">{{ result.skip_reason || result.errors.join('；') }}</p><div class="response-code"><pre class="gutter">{{ lineNumbers }}</pre><pre v-html="highlighted"></pre></div></template>
    </template>
    <div v-else class="execution-log"><p v-if="running">正在执行场景，请等待接口返回结果…</p><p v-for="item in logs" :key="item.id" :class="item.result.passed === false ? 'log-error' : 'log-success'"><strong>{{ item.name }}</strong><span>{{ item.result.skipped ? '跳过' : item.result.passed ? '通过' : '失败' }} · {{ item.result.duration_ms ?? '—' }} ms</span><small v-if="item.result.errors?.length">{{ item.result.errors.join('；') }}</small></p><p v-if="!logs.length && !running">尚无执行记录</p></div>
    <footer><PhCheckCircle :class="{good:summary.failed === 0 && summary.executed > 0}" weight="fill"/><span>{{ running ? '场景执行中' : summary.executed ? '场景执行完成' : '等待调试' }}</span><span>{{ summary.passed }} 个接口通过</span><span>{{ summary.failed }} 失败</span><span v-if="duration">{{ duration }}</span></footer>
  </section>
</template>
<script setup lang="ts">
import {computed,onBeforeUnmount,onMounted,ref} from 'vue';
import {useMessage} from 'naive-ui';
import {PhArrowsIn,PhArrowsOut,PhCheckCircle,PhCopy,PhPlayCircle,PhXCircle} from '@phosphor-icons/vue';
const props=defineProps<{result?:any;running:boolean;finishedAt?:string;summary:any;duration?:string;logs:any[]}>();
const mode=ref('result');const tab=ref('body');const fullscreen=ref(false);const message=useMessage();
const tabs=computed(()=>[{key:'body',label:'响应体'},{key:'headers',label:'响应头',count:Object.keys(props.result?.response_headers || {}).length},{key:'assertions',label:'断言结果',count:props.result?.assertions?.length || 0},{key:'extracted',label:'提取结果',count:Object.keys(props.result?.extracted || {}).length}]);
const passedAssertions=computed(()=>(props.result?.assertions || []).filter((a:any)=>a.passed === true || a.success === true).length);
const body=computed(()=>{const r=props.result;if(!r)return '';let value=tab.value === 'body' ? r.response_body : tab.value === 'headers' ? r.response_headers : tab.value === 'assertions' ? r.assertions : r.extracted; if(typeof value === 'string'){try{value=JSON.parse(value);}catch{return value;}}return JSON.stringify(value ?? {},null,2);});
const lineNumbers=computed(()=>body.value.split('\n').map((_,i)=>i+1).join('\n'));
const escape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
const highlighted=computed(()=>escape(body.value).replace(/("(?:\\.|[^"\\])*"\s*:)|("(?:\\.|[^"\\])*")|\b(true|false|null)\b|\b(-?\d+(?:\.\d+)?)\b/g,(match,key,string,literal)=>`<span class="${key?'json-key':string?'json-string':literal?'json-literal':'json-number'}">${match}</span>`));
async function copy(){try{await navigator.clipboard.writeText(body.value);message.success('已复制结果');}catch{message.error('复制失败');}}
function onEscape(event:KeyboardEvent){if(event.key==='Escape')fullscreen.value=false;}
onMounted(()=>window.addEventListener('keydown',onEscape));onBeforeUnmount(()=>window.removeEventListener('keydown',onEscape));
</script>
<style scoped>
.result-panel{display:flex;flex-direction:column;min-height:290px;border:1px solid #dfe7ed;border-radius:6px;background:#fff;overflow:hidden;position:relative}.result-panel.fullscreen{position:fixed;inset:12px;z-index:3000;box-shadow:0 0 0 30px #142a3b80}.result-panel>header{display:flex;gap:10px;align-items:center;min-height:43px;padding:0 16px;border-bottom:1px solid #e2e9ef}.result-panel nav{display:flex;gap:20px;align-items:center}.result-panel nav button{padding:10px 0;background:none;border:0;border-bottom:2px solid transparent;font-size:13px;color:#65758a;cursor:pointer;white-space:nowrap}.result-panel nav button.active{color:#00838e;border-color:#008d96;font-weight:600}.recent{margin-left:auto;color:#8190a3;font-size:11px;white-space:nowrap}.icon-button{border:0;background:none;display:inline-flex;align-items:center;justify-content:center;color:#62778c;width:28px;height:28px;cursor:pointer}.result-status{display:flex;align-items:center;gap:20px;padding:10px 16px 2px;font-size:12px;color:#45586c}.status-badge{display:flex;gap:4px;align-items:center;background:#e8f9ea;color:#1b9b43;padding:2px 6px;border-radius:4px}.status-badge.failed{background:#ffedf0;color:#d64051}.status-badge.skipped{background:#f0f3f6;color:#7b8d9f}.response-tabs{padding:0 16px;overflow-x:auto;flex:none}.response-tabs small{background:#f0f3f7;padding:1px 5px;margin-left:5px;border-radius:10px}.response-tabs .copy{margin-left:auto}.response-code{display:flex;gap:18px;background:#20303c;color:#e4edf4;padding:12px 16px;min-height:200px;max-height:370px;overflow:auto;flex:1}.fullscreen .response-code{max-height:none}.response-code pre{font:12px/21px 'SFMono-Regular',Consolas,monospace;margin:0;tab-size:2;white-space:pre}.response-code .gutter{color:#8095a6;user-select:none;text-align:right}.response-code :deep(.json-key){color:#80d7e5}.response-code :deep(.json-string){color:#b7d97e}.response-code :deep(.json-number){color:#a6dbee}.response-code :deep(.json-literal){color:#f7c574}.pending{display:flex;flex:1;align-items:center;justify-content:center;gap:10px;min-height:200px;background:#f8fafb;color:#8798aa;font-size:13px}.pending>svg{font-size:23px}.result-panel footer{display:flex;align-items:center;gap:12px;min-height:34px;padding:4px 16px;font-size:11px;color:#7a8c9e;border-top:1px solid #e2e9ef}.result-panel footer .good{color:#259d51}.errors{color:#c83247;font-size:12px;margin:8px 16px}.execution-log{flex:1;min-height:220px;max-height:370px;overflow:auto;background:#f8fafb;padding:14px 16px}.execution-log p{font-size:12px;display:flex;flex-wrap:wrap;gap:15px;border-bottom:1px solid #e2e9ef;padding-bottom:10px}.execution-log small{width:100%;color:#b83145}.log-error{color:#ca344b}.log-success{color:#258457}@media(max-width:700px){.recent{display:none}.result-status{gap:12px}.result-panel footer{flex-wrap:wrap}}
</style>
<style scoped>
.execution-details{padding:8px 16px;font-size:12px;color:#52677a;border-bottom:1px solid #e2e9ef}
.execution-details summary{cursor:pointer;color:#00838e}
.execution-details pre{max-height:240px;overflow:auto;white-space:pre;font:12px/21px monospace}
</style>
