/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/account/profile/all_user/': {
    /** @description 查询多个数据，返回多个数据 */
    get: operations['api_account_profile_all_user_retrieve'];
  };
  '/api/account/profile/change/': {
    post: operations['api_account_profile_change_create'];
  };
  '/api/account/profile/img_upload/': {
    post: operations['api_account_profile_img_upload_create'];
  };
  '/api/account/profile/login/': {
    post: operations['api_account_profile_login_create'];
  };
  '/api/account/profile/profile/': {
    /** @description 查询单个数，返回单个数据 */
    get: operations['api_account_profile_profile_retrieve'];
  };
  '/api/account/profile/reset_password/': {
    post: operations['api_account_profile_reset_password_create'];
  };
  '/api/case_api/case/': {
    get: operations['api_case_api_case_list'];
    post: operations['api_case_api_case_create'];
  };
  '/api/case_api/case/{id}/': {
    get: operations['api_case_api_case_retrieve'];
    put: operations['api_case_api_case_update'];
    delete: operations['api_case_api_case_destroy'];
    patch: operations['api_case_api_case_partial_update'];
  };
  '/api/case_api/endpoint/': {
    get: operations['api_case_api_endpoint_list'];
    post: operations['api_case_api_endpoint_create'];
  };
  '/api/case_api/endpoint/{id}/': {
    get: operations['api_case_api_endpoint_retrieve'];
    put: operations['api_case_api_endpoint_update'];
    delete: operations['api_case_api_endpoint_destroy'];
    patch: operations['api_case_api_endpoint_partial_update'];
  };
  '/api/case_ui/case/': {
    get: operations['api_case_ui_case_list'];
    post: operations['api_case_ui_case_create'];
  };
  '/api/case_ui/case/{id}/': {
    get: operations['api_case_ui_case_retrieve'];
    put: operations['api_case_ui_case_update'];
    delete: operations['api_case_ui_case_destroy'];
    patch: operations['api_case_ui_case_partial_update'];
  };
  '/api/case_ui/element/': {
    get: operations['api_case_ui_element_list'];
    post: operations['api_case_ui_element_create'];
  };
  '/api/case_ui/element/{id}/': {
    get: operations['api_case_ui_element_retrieve'];
    put: operations['api_case_ui_element_update'];
    delete: operations['api_case_ui_element_destroy'];
    patch: operations['api_case_ui_element_partial_update'];
  };
  '/api/project/config/': {
    get: operations['api_project_config_list'];
    post: operations['api_project_config_create'];
  };
  '/api/project/config/{id}/': {
    get: operations['api_project_config_retrieve'];
    put: operations['api_project_config_update'];
    delete: operations['api_project_config_destroy'];
    patch: operations['api_project_config_partial_update'];
  };
  '/api/project/project/': {
    get: operations['api_project_project_list'];
    post: operations['api_project_project_create'];
  };
  '/api/project/project/{id}/': {
    get: operations['api_project_project_retrieve'];
    put: operations['api_project_project_update'];
    delete: operations['api_project_project_destroy'];
    patch: operations['api_project_project_partial_update'];
  };
  '/api/schema/openapi.json': {
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     * - YAML: application/vnd.oai.openapi
     * - JSON: application/vnd.oai.openapi+json
     */
    get: operations['api_schema_openapi.json_retrieve'];
  };
  '/api/suite/run_result/': {
    get: operations['api_suite_run_result_list'];
  };
  '/api/suite/run_result/{id}/': {
    get: operations['api_suite_run_result_retrieve'];
  };
  '/api/suite/static/{path}': {
    get: operations['api_suite_static_retrieve'];
  };
  '/api/suite/suite/': {
    get: operations['api_suite_suite_list'];
    post: operations['api_suite_suite_create'];
  };
  '/api/suite/suite/{id}/': {
    get: operations['api_suite_suite_retrieve'];
    put: operations['api_suite_suite_update'];
    delete: operations['api_suite_suite_destroy'];
    patch: operations['api_suite_suite_partial_update'];
  };
  '/api/suite/suite/{id}/run/': {
    /** @description 执行测试套件 */
    post: operations['api_suite_suite_run_create'];
  };
  '/api/suite/suite/{id}/webhook/': {
    /** @description 执行测试套件 */
    get: operations['api_suite_suite_webhook_retrieve'];
    /** @description 执行测试套件 */
    post: operations['api_suite_suite_webhook_create'];
  };
  '/api/system/department/': {
    get: operations['api_system_department_list'];
    post: operations['api_system_department_create'];
  };
  '/api/system/department/{id}/': {
    get: operations['api_system_department_retrieve'];
    put: operations['api_system_department_update'];
    delete: operations['api_system_department_destroy'];
    patch: operations['api_system_department_partial_update'];
  };
  '/api/system/position/': {
    get: operations['api_system_position_list'];
    post: operations['api_system_position_create'];
  };
  '/api/system/position/{id}/': {
    get: operations['api_system_position_retrieve'];
    put: operations['api_system_position_update'];
    delete: operations['api_system_position_destroy'];
    patch: operations['api_system_position_partial_update'];
  };
  '/api/system/role/': {
    get: operations['api_system_role_list'];
    post: operations['api_system_role_create'];
  };
  '/api/system/role/{id}/': {
    get: operations['api_system_role_retrieve'];
    put: operations['api_system_role_update'];
    delete: operations['api_system_role_destroy'];
    patch: operations['api_system_role_partial_update'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description * `CLASS_NAME` - CLASS_NAME
     * * `CSS_SELECTOR` - CSS_SELECTOR
     * * `ID` - ID
     * * `LINK_TEXT` - LINK_TEXT
     * * `NAME` - NAME
     * * `PARTIAL_LINK_TEXT` - PARTIAL_LINK_TEXT
     * * `TAG_NAME` - TAG_NAME
     * * `XPATH` - XPATH
     * @enum {string}
     */
    ByEnum:
      | 'CLASS_NAME'
      | 'CSS_SELECTOR'
      | 'ID'
      | 'LINK_TEXT'
      | 'NAME'
      | 'PARTIAL_LINK_TEXT'
      | 'TAG_NAME'
      | 'XPATH';
    Case: {
      id: number;
      endpoint: components['schemas']['Endpoint'];
      /** 用例名称 */
      name: string;
      /** Allure标注 */
      allure?: {
        [key: string]: unknown;
      } | null;
      /** 接口用例参数 */
      api_args?: {
        [key: string]: unknown;
      } | null;
      /** 数据提取 */
      extract?: {
        [key: string]: unknown;
      } | null;
      /** 断言 */
      validate: {
        [key: string]: unknown;
      };
      project: number;
    };
    CaseUI: {
      id: number;
      usefixtures: unknown[];
      steps: components['schemas']['UIStep'][];
      /** 用例名称 */
      name: string;
      project: number;
    };
    Config: {
      id: number;
      /** Pytest配置脚本 */
      conftest?: string;
      project: number;
    };
    Department: {
      id: number;
      leader_img: string;
      leader_name: string;
      /** 部门名称 */
      name: string;
      /** 部门简介 */
      intro?: string;
      leader?: number | null;
    };
    Element: {
      id: number;
      /** 元素名称 */
      name: string;
      /** 定位方式 */
      by?: components['schemas']['ByEnum'];
      /** 定位表达式 */
      value: string;
      project: number;
    };
    Endpoint: {
      id: number;
      /** 接口名称 */
      name: string;
      method: string;
      url: string;
      /** 查询字符串 */
      params?: {
        [key: string]: unknown;
      } | null;
      /** 表单参数 */
      data?: {
        [key: string]: unknown;
      } | null;
      /** JSON参数 */
      json?: {
        [key: string]: unknown;
      } | null;
      cookies?: {
        [key: string]: unknown;
      } | null;
      /** 请求头 */
      headers?: {
        [key: string]: unknown;
      } | null;
      project: number;
    };
    HeadImage: {
      id: number;
      user: string;
      /**
       * 头像地址
       * Format: uri
       */
      img: string;
    };
    Login: {
      username: string;
      password: string;
    };
    PaginatedCaseList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Case'][];
    };
    PaginatedCaseUIList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['CaseUI'][];
    };
    PaginatedConfigList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Config'][];
    };
    PaginatedDepartmentList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Department'][];
    };
    PaginatedElementList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Element'][];
    };
    PaginatedEndpointList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Endpoint'][];
    };
    PaginatedPositionList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Position'][];
    };
    PaginatedProjectList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Project'][];
    };
    PaginatedRoleList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Role'][];
    };
    PaginatedRunResultList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['RunResult'][];
    };
    PaginatedSuiteList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Suite'][];
    };
    PatchedCase: {
      id?: number;
      endpoint?: components['schemas']['Endpoint'];
      /** 用例名称 */
      name?: string;
      /** Allure标注 */
      allure?: {
        [key: string]: unknown;
      } | null;
      /** 接口用例参数 */
      api_args?: {
        [key: string]: unknown;
      } | null;
      /** 数据提取 */
      extract?: {
        [key: string]: unknown;
      } | null;
      /** 断言 */
      validate?: {
        [key: string]: unknown;
      };
      project?: number;
    };
    PatchedCaseUI: {
      id?: number;
      usefixtures?: unknown[];
      steps?: components['schemas']['UIStep'][];
      /** 用例名称 */
      name?: string;
      project?: number;
    };
    PatchedConfig: {
      id?: number;
      /** Pytest配置脚本 */
      conftest?: string;
      project?: number;
    };
    PatchedDepartment: {
      id?: number;
      leader_img?: string;
      leader_name?: string;
      /** 部门名称 */
      name?: string;
      /** 部门简介 */
      intro?: string;
      leader?: number | null;
    };
    PatchedElement: {
      id?: number;
      /** 元素名称 */
      name?: string;
      /** 定位方式 */
      by?: components['schemas']['ByEnum'];
      /** 定位表达式 */
      value?: string;
      project?: number;
    };
    PatchedEndpoint: {
      id?: number;
      /** 接口名称 */
      name?: string;
      method?: string;
      url?: string;
      /** 查询字符串 */
      params?: {
        [key: string]: unknown;
      } | null;
      /** 表单参数 */
      data?: {
        [key: string]: unknown;
      } | null;
      /** JSON参数 */
      json?: {
        [key: string]: unknown;
      } | null;
      cookies?: {
        [key: string]: unknown;
      } | null;
      /** 请求头 */
      headers?: {
        [key: string]: unknown;
      } | null;
      project?: number;
    };
    PatchedPosition: {
      id?: number;
      /** 职位名称 */
      name?: string;
      /** 负责人 */
      is_leader?: boolean;
    };
    PatchedProject: {
      id?: number;
      pm_profile?: string;
      /** 项目名称 */
      name?: string;
      /** 项目简介 */
      intro?: string;
      /** 项目地址 */
      url?: string;
      pm?: number | null;
      user_list?: number[];
    };
    PatchedRole: {
      id?: number;
      user?: number;
      department?: number;
      position?: number;
    };
    PatchedSuite: {
      id?: number;
      /** 套件名称 */
      name?: string;
      /** 套件描述 */
      description?: string;
      /** 运行类型 */
      run_type?: components['schemas']['RunTypeEnum'];
      /** Cron表达式 */
      cron?: string;
      /** Hook密钥 */
      hook_key?: string;
      project?: number;
      schedule?: number | null;
      case_ui_list?: number[];
      case_api_list?: number[];
    };
    Position: {
      id: number;
      /** 职位名称 */
      name: string;
      /** 负责人 */
      is_leader?: boolean;
    };
    Profile: {
      id: number;
      token: string;
      token_expires_at: string;
      user: string;
      role_list: readonly components['schemas']['RoleShow'][];
      /** 昵称 */
      name: string;
      /** 头像地址 */
      head_img: string;
    };
    Project: {
      id: number;
      pm_profile: string;
      /** 项目名称 */
      name: string;
      /** 项目简介 */
      intro?: string;
      /** 项目地址 */
      url?: string;
      pm?: number | null;
      user_list?: number[];
    };
    ResetPass: {
      new_password: string;
      confirm_password: string;
    };
    Role: {
      id: number;
      user: number;
      department: number;
      position: number;
    };
    RoleShow: {
      department: string;
      position: string;
      is_leader: boolean;
    };
    RunResult: {
      id: number;
      report_url: string;
      log_url: string;
      artifacts_url: string;
      /** 测试通过 */
      is_pass?: boolean;
      /** 执行状态 */
      status?: components['schemas']['StatusEnum'];
      /**
       * 创建时间
       * Format: date-time
       */
      create_datetime: string;
      /**
       * 更新时间
       * Format: date-time
       */
      update_datetime: string;
      suite: number;
      project: number;
    };
    /**
     * @description * `O` - 单次执行
     * * `C` - Cron
     * * `W` - WebHook
     * @enum {string}
     */
    RunTypeEnum: 'O' | 'C' | 'W';
    /**
     * @description * `0` - 初始化
     * * `1` - 准备开始
     * * `2` - 正在执行
     * * `3` - 正在正常报告
     * * `4` - 执行完毕
     * * `-1` - 执行出错
     * @enum {integer}
     */
    StatusEnum: 0 | 1 | 2 | 3 | 4 | -1;
    Suite: {
      id: number;
      /** 套件名称 */
      name: string;
      /** 套件描述 */
      description?: string;
      /** 运行类型 */
      run_type?: components['schemas']['RunTypeEnum'];
      /** Cron表达式 */
      cron?: string;
      /** Hook密钥 */
      hook_key?: string;
      project: number;
      schedule?: number | null;
      case_ui_list?: number[];
      case_api_list?: number[];
    };
    UIStep: {
      步骤: string;
      步骤名: string;
      关键字: string;
      参数: string;
      /** blankfield */
      _BlankField: unknown[];
    };
    UserList: {
      id: number;
      /** 昵称 */
      name: string;
      /** 头像地址 */
      head_img: string;
      user: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** @description 查询多个数据，返回多个数据 */
  api_account_profile_all_user_retrieve: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['UserList'];
        };
      };
    };
  };
  api_account_profile_change_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Profile'];
        'application/x-www-form-urlencoded': components['schemas']['Profile'];
        'multipart/form-data': components['schemas']['Profile'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  api_account_profile_img_upload_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['HeadImage'];
        'application/x-www-form-urlencoded': components['schemas']['HeadImage'];
        'multipart/form-data': components['schemas']['HeadImage'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['HeadImage'];
        };
      };
    };
  };
  api_account_profile_login_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
        'application/x-www-form-urlencoded': components['schemas']['Login'];
        'multipart/form-data': components['schemas']['Login'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  /** @description 查询单个数，返回单个数据 */
  api_account_profile_profile_retrieve: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  api_account_profile_reset_password_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPass'];
        'application/x-www-form-urlencoded': components['schemas']['ResetPass'];
        'multipart/form-data': components['schemas']['ResetPass'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_case_api_case_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedCaseList'];
        };
      };
    };
  };
  api_case_api_case_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Case'];
        'application/x-www-form-urlencoded': components['schemas']['Case'];
        'multipart/form-data': components['schemas']['Case'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Case'];
        };
      };
    };
  };
  api_case_api_case_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Case'];
        };
      };
    };
  };
  api_case_api_case_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Case'];
        'application/x-www-form-urlencoded': components['schemas']['Case'];
        'multipart/form-data': components['schemas']['Case'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Case'];
        };
      };
    };
  };
  api_case_api_case_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_case_api_case_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedCase'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedCase'];
        'multipart/form-data': components['schemas']['PatchedCase'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Case'];
        };
      };
    };
  };
  api_case_api_endpoint_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedEndpointList'];
        };
      };
    };
  };
  api_case_api_endpoint_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Endpoint'];
        'application/x-www-form-urlencoded': components['schemas']['Endpoint'];
        'multipart/form-data': components['schemas']['Endpoint'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  api_case_api_endpoint_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  api_case_api_endpoint_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Endpoint'];
        'application/x-www-form-urlencoded': components['schemas']['Endpoint'];
        'multipart/form-data': components['schemas']['Endpoint'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  api_case_api_endpoint_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_case_api_endpoint_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedEndpoint'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedEndpoint'];
        'multipart/form-data': components['schemas']['PatchedEndpoint'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  api_case_ui_case_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedCaseUIList'];
        };
      };
    };
  };
  api_case_ui_case_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['CaseUI'];
        'application/x-www-form-urlencoded': components['schemas']['CaseUI'];
        'multipart/form-data': components['schemas']['CaseUI'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['CaseUI'];
        };
      };
    };
  };
  api_case_ui_case_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['CaseUI'];
        };
      };
    };
  };
  api_case_ui_case_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CaseUI'];
        'application/x-www-form-urlencoded': components['schemas']['CaseUI'];
        'multipart/form-data': components['schemas']['CaseUI'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['CaseUI'];
        };
      };
    };
  };
  api_case_ui_case_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_case_ui_case_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this case. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedCaseUI'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedCaseUI'];
        'multipart/form-data': components['schemas']['PatchedCaseUI'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['CaseUI'];
        };
      };
    };
  };
  api_case_ui_element_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedElementList'];
        };
      };
    };
  };
  api_case_ui_element_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Element'];
        'application/x-www-form-urlencoded': components['schemas']['Element'];
        'multipart/form-data': components['schemas']['Element'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  api_case_ui_element_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  api_case_ui_element_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Element'];
        'application/x-www-form-urlencoded': components['schemas']['Element'];
        'multipart/form-data': components['schemas']['Element'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  api_case_ui_element_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_case_ui_element_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedElement'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedElement'];
        'multipart/form-data': components['schemas']['PatchedElement'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  api_project_config_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedConfigList'];
        };
      };
    };
  };
  api_project_config_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Config'];
        'application/x-www-form-urlencoded': components['schemas']['Config'];
        'multipart/form-data': components['schemas']['Config'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Config'];
        };
      };
    };
  };
  api_project_config_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this config. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Config'];
        };
      };
    };
  };
  api_project_config_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this config. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Config'];
        'application/x-www-form-urlencoded': components['schemas']['Config'];
        'multipart/form-data': components['schemas']['Config'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Config'];
        };
      };
    };
  };
  api_project_config_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this config. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_project_config_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this config. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedConfig'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedConfig'];
        'multipart/form-data': components['schemas']['PatchedConfig'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Config'];
        };
      };
    };
  };
  api_project_project_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedProjectList'];
        };
      };
    };
  };
  api_project_project_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
        'application/x-www-form-urlencoded': components['schemas']['Project'];
        'multipart/form-data': components['schemas']['Project'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  api_project_project_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  api_project_project_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
        'application/x-www-form-urlencoded': components['schemas']['Project'];
        'multipart/form-data': components['schemas']['Project'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  api_project_project_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_project_project_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedProject'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedProject'];
        'multipart/form-data': components['schemas']['PatchedProject'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  /**
   * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   */
  'api_schema_openapi.json_retrieve': {
    parameters: {
      query?: {
        format?: 'json' | 'yaml';
        lang?:
          | 'af'
          | 'ar'
          | 'ar-dz'
          | 'ast'
          | 'az'
          | 'be'
          | 'bg'
          | 'bn'
          | 'br'
          | 'bs'
          | 'ca'
          | 'ckb'
          | 'cs'
          | 'cy'
          | 'da'
          | 'de'
          | 'dsb'
          | 'el'
          | 'en'
          | 'en-au'
          | 'en-gb'
          | 'eo'
          | 'es'
          | 'es-ar'
          | 'es-co'
          | 'es-mx'
          | 'es-ni'
          | 'es-ve'
          | 'et'
          | 'eu'
          | 'fa'
          | 'fi'
          | 'fr'
          | 'fy'
          | 'ga'
          | 'gd'
          | 'gl'
          | 'he'
          | 'hi'
          | 'hr'
          | 'hsb'
          | 'hu'
          | 'hy'
          | 'ia'
          | 'id'
          | 'ig'
          | 'io'
          | 'is'
          | 'it'
          | 'ja'
          | 'ka'
          | 'kab'
          | 'kk'
          | 'km'
          | 'kn'
          | 'ko'
          | 'ky'
          | 'lb'
          | 'lt'
          | 'lv'
          | 'mk'
          | 'ml'
          | 'mn'
          | 'mr'
          | 'ms'
          | 'my'
          | 'nb'
          | 'ne'
          | 'nl'
          | 'nn'
          | 'os'
          | 'pa'
          | 'pl'
          | 'pt'
          | 'pt-br'
          | 'ro'
          | 'ru'
          | 'sk'
          | 'sl'
          | 'sq'
          | 'sr'
          | 'sr-latn'
          | 'sv'
          | 'sw'
          | 'ta'
          | 'te'
          | 'tg'
          | 'th'
          | 'tk'
          | 'tr'
          | 'tt'
          | 'udm'
          | 'uk'
          | 'ur'
          | 'uz'
          | 'vi'
          | 'zh-hans'
          | 'zh-hant';
      };
    };
    responses: {
      200: {
        content: {
          'application/vnd.oai.openapi': {
            [key: string]: unknown;
          };
          'application/yaml': {
            [key: string]: unknown;
          };
          'application/vnd.oai.openapi+json': {
            [key: string]: unknown;
          };
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  api_suite_run_result_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedRunResultList'];
        };
      };
    };
  };
  api_suite_run_result_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this run result. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['RunResult'];
        };
      };
    };
  };
  api_suite_static_retrieve: {
    parameters: {
      path: {
        path: string;
      };
    };
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
  api_suite_suite_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedSuiteList'];
        };
      };
    };
  };
  api_suite_suite_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  api_suite_suite_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  api_suite_suite_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  api_suite_suite_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_suite_suite_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedSuite'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedSuite'];
        'multipart/form-data': components['schemas']['PatchedSuite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  api_suite_suite_run_create: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  api_suite_suite_webhook_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  api_suite_suite_webhook_create: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  api_system_department_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedDepartmentList'];
        };
      };
    };
  };
  api_system_department_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Department'];
        'application/x-www-form-urlencoded': components['schemas']['Department'];
        'multipart/form-data': components['schemas']['Department'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  api_system_department_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  api_system_department_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Department'];
        'application/x-www-form-urlencoded': components['schemas']['Department'];
        'multipart/form-data': components['schemas']['Department'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  api_system_department_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_system_department_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedDepartment'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedDepartment'];
        'multipart/form-data': components['schemas']['PatchedDepartment'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  api_system_position_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedPositionList'];
        };
      };
    };
  };
  api_system_position_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Position'];
        'application/x-www-form-urlencoded': components['schemas']['Position'];
        'multipart/form-data': components['schemas']['Position'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  api_system_position_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  api_system_position_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Position'];
        'application/x-www-form-urlencoded': components['schemas']['Position'];
        'multipart/form-data': components['schemas']['Position'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  api_system_position_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_system_position_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedPosition'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedPosition'];
        'multipart/form-data': components['schemas']['PatchedPosition'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  api_system_role_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedRoleList'];
        };
      };
    };
  };
  api_system_role_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Role'];
        'application/x-www-form-urlencoded': components['schemas']['Role'];
        'multipart/form-data': components['schemas']['Role'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  api_system_role_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  api_system_role_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Role'];
        'application/x-www-form-urlencoded': components['schemas']['Role'];
        'multipart/form-data': components['schemas']['Role'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  api_system_role_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  api_system_role_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedRole'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedRole'];
        'multipart/form-data': components['schemas']['PatchedRole'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
}
