"""
Django settings for Tesla project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载项目根目录 .env 中的环境变量（如 DEEPSEEK_API_KEY）
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-*#(kb(5xb_swrb3s-&ae)6=-2n=a0zlw@)w#t+_+vfbad4p=e$",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "true").strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")
    if host.strip()
]

# 用于通知消息中的平台执行报告绝对地址。线上环境请在 .env 中配置，
# 例如 REPORT_PUBLIC_BASE_URL=https://test.example.com
REPORT_PUBLIC_BASE_URL = os.getenv("REPORT_PUBLIC_BASE_URL", "http://localhost:8001").rstrip("/")

# Webhook 签名允许的时间偏差。生产环境可通过环境变量收紧或放宽，默认 5 分钟。
try:
    WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = max(
        30, int(os.getenv("WEBHOOK_SIGNATURE_TOLERANCE_SECONDS", "300"))
    )
except (TypeError, ValueError):
    WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = 300

# 执行目录与本地日志的保留天数。数据库中的执行记录和原生报告不受影响。
try:
    FILE_RETENTION_DAYS = max(1, int(os.getenv("FILE_RETENTION_DAYS", "15")))
except (TypeError, ValueError):
    FILE_RETENTION_DAYS = 15

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",  # 提供Token支持
    "drf_spectacular",  # 插件的核心，生成OpenAPI
    "drf_spectacular_sidecar",  # 插件附属，生成HTML文档
    "django_q",  # 使用下划线
    "corsheaders", # 全局自动添加响应头
    "account",
    "system",
    "project",
    "case_api",
    "case_ui",
    "suite",
    "ai_assistant",
    "execution_template",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Tesla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Tesla.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "sqlite").strip().lower()

if DATABASE_ENGINE in {"mysql", "django.db.backends.mysql"}:
    import pymysql

    pymysql.install_as_MySQLdb()

    mysql_options = {
        "charset": "utf8mb4",
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    }
    mysql_socket = os.getenv("DATABASE_SOCKET", "").strip()
    if mysql_socket:
        mysql_options["unix_socket"] = mysql_socket

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DATABASE_NAME", "test_platform"),
            "USER": os.getenv("DATABASE_USER", "test_platform"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", ""),
            "HOST": os.getenv("DATABASE_HOST", ""),
            "PORT": os.getenv("DATABASE_PORT", ""),
            "OPTIONS": mysql_options,
            "CONN_MAX_AGE": max(0, int(os.getenv("DATABASE_CONN_MAX_AGE", "60"))),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "zh-hans"

# 平台页面、Cron 表达式和调度器统一使用中国标准时间，避免默认 America/Chicago 造成触发时间偏移。
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "api/"  # 显示文件资源的前缀

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

NNNNNNNN = "BeiFan"

REST_FRAMEWORK = {  # DRF的设置  让DRF 使用drf_spectacular生成OPENAPI
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": ["Tesla.renderer.CodeResultMessageRenderer"],
    "DEFAULT_PAGINATION_CLASS": "Tesla.pagination.PageNumberPagination",
}

SPECTACULAR_SETTINGS = {  # drf_spectacular的设置
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# DeepSeek AI 对话配置（API Key 从环境变量读取，避免写入代码库）
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_MODEL = "deepseek-chat"

Q_CLUSTER = {
    "orm": "default",
    "timeout": 60 * 10,
    "retry": 60 * 10 * 2,
    "workers": max(1, int(os.getenv("DJANGO_Q_WORKERS", "2"))),
}


FRAMEWORK_DIR = "fullstack_framework"
CORS_ORIGIN_ALLOW_ALL =True # 所有网址都允CORS
X_FRAME_OPTIONS = 'SAMEORIGIN'
