"""
Django settings for Tesla project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import base64
import hashlib
import os
from pathlib import Path

from corsheaders.defaults import default_headers
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 加载项目根目录 .env 中的环境变量（如 DEEPSEEK_API_KEY）
load_dotenv(BASE_DIR / ".env")

def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return bool(default)
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ImproperlyConfigured(f"环境变量 {name} 必须为 true 或 false。")


def env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# development 用于本地开发；production 用于部署。禁止使用隐式 DEBUG
# 推断环境，避免生产因漏配单个变量而回退到不安全状态。
DJANGO_ENV = os.getenv("DJANGO_ENV", "development").strip().lower()
if DJANGO_ENV not in {"development", "production"}:
    raise ImproperlyConfigured("DJANGO_ENV 仅支持 development 或 production。")
IS_PRODUCTION = DJANGO_ENV == "production"

DEVELOPMENT_SECRET_KEY = "django-insecure-local-development-only-change-me"
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "").strip() or DEVELOPMENT_SECRET_KEY
DEBUG = env_bool("DJANGO_DEBUG", default=not IS_PRODUCTION)
ALLOWED_HOSTS = env_list(
    "DJANGO_ALLOWED_HOSTS",
    "127.0.0.1,localhost" if not IS_PRODUCTION else "",
)

if IS_PRODUCTION:
    if DEBUG:
        raise ImproperlyConfigured("生产环境禁止开启 DJANGO_DEBUG。")
    if SECRET_KEY == DEVELOPMENT_SECRET_KEY or SECRET_KEY.startswith("django-insecure-") or len(SECRET_KEY) < 50:
        raise ImproperlyConfigured("生产环境必须配置至少 50 位的强随机 DJANGO_SECRET_KEY。")
    if not ALLOWED_HOSTS or "*" in ALLOWED_HOSTS:
        raise ImproperlyConfigured("生产环境必须配置明确的 DJANGO_ALLOWED_HOSTS，不允许使用 *。")

# 敏感字段静态加密密钥。第一个密钥负责新写入，后续密钥用于读取轮换前的
# 历史密文。生产环境必须独立配置，不能复用 Django SECRET_KEY。
DATA_ENCRYPTION_KEYS = tuple(env_list("DATA_ENCRYPTION_KEYS"))
if IS_PRODUCTION and not DATA_ENCRYPTION_KEYS:
    raise ImproperlyConfigured("生产环境必须配置 DATA_ENCRYPTION_KEYS 用于敏感数据静态加密。")
if not DATA_ENCRYPTION_KEYS:
    development_key = base64.urlsafe_b64encode(
        hashlib.sha256(f"local-data-encryption:{SECRET_KEY}".encode("utf-8")).digest()
    ).decode("ascii")
    DATA_ENCRYPTION_KEYS = (development_key,)

# 在生产环境默认关闭 OpenAPI/Swagger/Redoc，确有运维需求时再显式开启。
API_DOCS_ENABLED = env_bool("DJANGO_API_DOCS_ENABLED", default=not IS_PRODUCTION)

# 用于通知消息中的平台执行报告绝对地址。线上环境请在 .env 中配置，
# 例如 REPORT_PUBLIC_BASE_URL=https://test.example.com
REPORT_PUBLIC_BASE_URL = os.getenv("REPORT_PUBLIC_BASE_URL", "http://localhost:8001").rstrip("/")

# Webhook 签名允许的时间偏差。生产环境可通过环境变量收紧或放宽，默认 5 分钟。
try:
    WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = max(
        30, int(os.getenv("WEBHOOK_SIGNATURE_TOLERANCE_SECONDS", "300"))
    )
except (TypeError, ValueError):
    WEBHOOK_SIGNATURE_TOLERANCE_SECONDS = 300

# 接口执行文件与性能报告的保留天数。性能报告过期后会连同指标明细和运行产物自动删除。
try:
    FILE_RETENTION_DAYS = max(1, int(os.getenv("FILE_RETENTION_DAYS", "15")))
except (TypeError, ValueError):
    FILE_RETENTION_DAYS = 15

# 动态函数通过 Unix Socket 交给无网络执行器；开发环境可在执行器未启动时使用隔离子进程。
DYNAMIC_FUNCTION_SOCKET = os.getenv("DYNAMIC_FUNCTION_SOCKET", "/run/dynamic-functions/worker.sock")
try:
    DYNAMIC_FUNCTION_TIMEOUT_SECONDS = max(1, min(10, int(os.getenv("DYNAMIC_FUNCTION_TIMEOUT_SECONDS", "3"))))
except (TypeError, ValueError):
    DYNAMIC_FUNCTION_TIMEOUT_SECONDS = 3
try:
    DYNAMIC_FUNCTION_MEMORY_MB = max(64, min(512, int(os.getenv("DYNAMIC_FUNCTION_MEMORY_MB", "128"))))
except (TypeError, ValueError):
    DYNAMIC_FUNCTION_MEMORY_MB = 128
DYNAMIC_FUNCTION_ALLOW_LOCAL_FALLBACK = env_bool("DYNAMIC_FUNCTION_ALLOW_LOCAL_FALLBACK", default=not IS_PRODUCTION)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework.authtoken",  # 提供Token支持
    "drf_spectacular",  # 插件的核心，生成OpenAPI
    "drf_spectacular_sidecar",  # 插件附属，生成HTML文档
    "django_q",  # 使用下划线
    "corsheaders", # 全局自动添加响应头
    "account",
    "system",
    "project",
    "case_api",
    "case_ui",
    "suite",
    "ai_assistant",
    "execution_template",
    "monitor",
    "performance",
    "case_app",
    "execution_control.apps.ExecutionControlConfig",
]

# 统一执行控制中心：心跳超过该时间未更新即认为执行器离线。
EXECUTION_WORKER_OFFLINE_SECONDS = max(
    15, int(os.getenv("EXECUTION_WORKER_OFFLINE_SECONDS", "45"))
)
# 等待任务超过该时间后才进行执行器诊断，避免刚入队时误报。
EXECUTION_QUEUE_DIAGNOSIS_SECONDS = max(
    10, int(os.getenv("EXECUTION_QUEUE_DIAGNOSIS_SECONDS", "30"))
)
# Appium 节点由 Django-Q 每分钟探活；超过两个检查周期仍无成功心跳则离线。
APPIUM_HEALTH_CHECK_TIMEOUT_SECONDS = max(
    1, int(os.getenv("APPIUM_HEALTH_CHECK_TIMEOUT_SECONDS", "5"))
)
APPIUM_NODE_OFFLINE_SECONDS = max(
    30, int(os.getenv("APPIUM_NODE_OFFLINE_SECONDS", "120"))
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Tesla.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Tesla.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASE_ENGINE = os.getenv("DATABASE_ENGINE", "sqlite").strip().lower()

if DATABASE_ENGINE in {"mysql", "django.db.backends.mysql"}:
    import pymysql

    pymysql.install_as_MySQLdb()

    mysql_options = {
        "charset": "utf8mb4",
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    }
    mysql_socket = os.getenv("DATABASE_SOCKET", "").strip()
    if mysql_socket:
        mysql_options["unix_socket"] = mysql_socket

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DATABASE_NAME", "test_platform"),
            "USER": os.getenv("DATABASE_USER", "test_platform"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", ""),
            "HOST": os.getenv("DATABASE_HOST", ""),
            "PORT": os.getenv("DATABASE_PORT", ""),
            "OPTIONS": mysql_options,
            "CONN_MAX_AGE": max(0, int(os.getenv("DATABASE_CONN_MAX_AGE", "60"))),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "zh-hans"

# 平台页面、Cron 表达式和调度器统一使用中国标准时间，避免默认 America/Chicago 造成触发时间偏移。
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = "api/"  # 显示文件资源的前缀
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {  # DRF的设置  让DRF 使用drf_spectacular生成OPENAPI
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "account.authentication.ExpiringTokenAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": ["Tesla.renderer.CodeResultMessageRenderer"],
    "DEFAULT_PAGINATION_CLASS": "Tesla.pagination.PageNumberPagination",
}

# 平台登录令牌固定有效 1 小时。该限制由服务端强制执行，不依赖前端缓存。
PLATFORM_TOKEN_TTL_SECONDS = 60 * 60

SPECTACULAR_SETTINGS = {  # drf_spectacular的设置
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
    "REDOC_DIST": "SIDECAR",
}

# DeepSeek AI 对话配置（API Key 从环境变量读取，避免写入代码库）
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
DEEPSEEK_MODEL = "deepseek-chat"

MAX_SUITE_EXECUTION_TIMEOUT_SECONDS = 86400
EXECUTION_TASK_FINISHING_GRACE_SECONDS = 300
execution_task_timeout_seconds = max(
    MAX_SUITE_EXECUTION_TIMEOUT_SECONDS + EXECUTION_TASK_FINISHING_GRACE_SECONDS,
    int(os.getenv("EXECUTION_TASK_TIMEOUT_SECONDS", "86700")),
)

Q_CLUSTER = {
    "orm": "default",
    # UI/App 执行可能超过 10 分钟。retry 必须大于 timeout，否则长任务
    # 会被队列重复投递，造成同一设备被重复占用。
    "timeout": execution_task_timeout_seconds,
    "retry": execution_task_timeout_seconds + 60,
    "workers": max(1, int(os.getenv("DJANGO_Q_WORKERS", "2"))),
}


FRAMEWORK_DIR = "fullstack_framework"

# 开发环境默认允许跨域，方便 Vite 本地调试；生产环境默认仅允许
# Nginx 同源请求。需要独立前端域名时，通过白名单显式配置。
CORS_ALLOW_ALL_ORIGINS = env_bool("DJANGO_CORS_ALLOW_ALL", default=not IS_PRODUCTION)
if IS_PRODUCTION and CORS_ALLOW_ALL_ORIGINS:
    raise ImproperlyConfigured("生产环境禁止开启 DJANGO_CORS_ALLOW_ALL。")
CORS_ALLOWED_ORIGINS = env_list("DJANGO_CORS_ALLOWED_ORIGINS")
CORS_ALLOW_CREDENTIALS = env_bool("DJANGO_CORS_ALLOW_CREDENTIALS", default=False)
CORS_ALLOW_HEADERS = (*default_headers, "x-tenant-id")
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# Nginx/Ingress 应传递 X-Forwarded-Proto。HTTPS 生产部署保持以下安全默认值；
# 暂时使用 HTTP 的私网部署必须在 backend.env 中显式关闭相关项。
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = env_bool("DJANGO_SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool("DJANGO_SESSION_COOKIE_SECURE", default=IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool("DJANGO_CSRF_COOKIE_SECURE", default=IS_PRODUCTION)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"
SECURE_HSTS_SECONDS = max(0, int(os.getenv("DJANGO_SECURE_HSTS_SECONDS", "31536000" if IS_PRODUCTION and SECURE_SSL_REDIRECT else "0")))
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = env_bool("DJANGO_SECURE_HSTS_PRELOAD", default=False)
X_FRAME_OPTIONS = "SAMEORIGIN"
