server {
	listen 8211 default_server;

	root /home/ubuntu/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;
	
	# head_img
	location /api/account/static/ {
        alias /home/ubuntu/python/account/static/;	
	}
	
	# report
	location /api/suite/static/ {
        alias /home/ubuntu/python/upload_yaml/;	
	}
	
	# API
	location /api/ {
        proxy_pass http://127.0.0.1:8213/api/;
	}
	

	location / {
		# First attempt to serve request as file, then
		# as directory, then fall back to displaying a 404.
		try_files $uri $uri/ index.html;
	}

}
