# Generated by Django 4.2.3 on 2023-08-15 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="user",
        ),
        migrations.AddField(
            model_name="project",
            name="pm",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="project_pm_list",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="user_list",
            field=models.ManyToManyField(
                blank=True, related_name="project_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
