# Generated by Django 4.2.3 on 2026-08-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_user_project_pm_project_user_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='环境名称')),
                ('base_url', models.CharField(max_length=256, verbose_name='环境地址')),
                ('auth_enabled', models.BooleanField(default=False, verbose_name='启用自动登录')),
                ('login_url', models.CharField(blank=True, max_length=256, verbose_name='登录接口')),
                ('login_method', models.CharField(default='POST', max_length=8, verbose_name='登录方法')),
                ('login_headers', models.JSONField(blank=True, default=dict, verbose_name='登录请求头')),
                ('login_params', models.JSONField(blank=True, default=dict, verbose_name='登录查询参数')),
                ('login_data', models.JSONField(blank=True, default=dict, verbose_name='登录表单参数')),
                ('login_json', models.JSONField(blank=True, default=dict, verbose_name='登录 JSON 参数')),
                ('token_jsonpath', models.CharField(blank=True, max_length=256, verbose_name='Token 提取表达式')),
                ('token_name', models.CharField(default='token', max_length=64, verbose_name='变量名')),
                ('token_header', models.CharField(default='Authorization', max_length=64, verbose_name='Token 请求头')),
                ('token_prefix', models.CharField(blank=True, default='Bearer ', max_length=64, verbose_name='Token 前缀')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='project.project')),
            ],
            options={
                'ordering': ['project_id', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='environment',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_environment_name'),
        ),
    ]
