# Generated by Django 4.2.3 on 2026-08-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_environment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
