# Generated by Django 4.2.3 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_remove_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(
                choices=[("Dev", "Dev"), ("Test", "Test"), ("Pre", "Pre"), ("Prod", "Prod")],
                default="Test",
                max_length=64,
                verbose_name="环境名称",
            ),
        ),
    ]
