# Generated by Django 4.2.3 on 2026-08-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_environment_name_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicFunction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='函数名称')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='函数说明')),
                ('code', models.TextField(verbose_name='函数代码')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_functions', to='project.project')),
            ],
            options={
                'ordering': ['project_id', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dynamicfunction',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_dynamic_function'),
        ),
    ]
