# Generated by Django 4.2.3 on 2026-08-08 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_dynamicfunction_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dynamicfunction',
            options={'ordering': ['id']},
        ),
        migrations.RemoveConstraint(
            model_name='dynamicfunction',
            name='unique_project_dynamic_function',
        ),
        migrations.AlterField(
            model_name='dynamicfunction',
            name='name',
            field=models.CharField(blank=True, default='functions', max_length=64, verbose_name='函数名称'),
        ),
        migrations.AlterField(
            model_name='dynamicfunction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_functions', to='project.project'),
        ),
    ]
