# Generated by Django 4.2.3 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_alter_dynamicfunction_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="cached_token",
            field=models.TextField(blank=True, default="", verbose_name="共享 Token 缓存"),
        ),
        migrations.AddField(
            model_name="environment",
            name="token_expires_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Token 过期时间"),
        ),
        migrations.AddField(
            model_name="environment",
            name="token_refreshed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Token 刷新时间"),
        ),
        migrations.AddField(
            model_name="environment",
            name="token_ttl",
            field=models.PositiveIntegerField(default=1800, verbose_name="Token 默认有效期（秒）"),
        ),
    ]
