# Generated by Django 4.2.3 on 2026-08-20 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_databaseconnection_allow_write'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='变量名')),
                ('value', models.TextField(blank=True, default='', verbose_name='变量值')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='project.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='projectvariable',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_variable_name'),
        ),
    ]
