# Generated by Django 4.2.3 on 2026-08-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_dynamicfunction_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='项目简介'),
        ),
    ]
