# Generated by Django 4.2.3 on 2026-08-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_alter_project_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='SSH Host'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_port',
            field=models.PositiveIntegerField(default=22, verbose_name='SSH Port'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_private_key_passphrase',
            field=models.CharField(blank=True, max_length=512, verbose_name='SSH 私钥口令'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_private_key_path',
            field=models.CharField(blank=True, max_length=512, verbose_name='SSH 私钥路径'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_strict_host_key',
            field=models.BooleanField(default=True, verbose_name='校验 SSH 主机指纹'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='ssh_username',
            field=models.CharField(blank=True, max_length=128, verbose_name='SSH 用户名'),
        ),
        migrations.AddField(
            model_name='databaseconnection',
            name='use_ssh_tunnel',
            field=models.BooleanField(default=False, verbose_name='使用 SSH 隧道'),
        ),
    ]
