# Generated by Django 4.2.3 on 2026-09-04 23:51

import Tesla.model_fields
import case_app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0021_environment_browser_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='应用名称')),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=16, verbose_name='平台')),
                ('package_name', models.CharField(max_length=255, verbose_name='Package Name')),
                ('main_activity', models.CharField(blank=True, default='', max_length=255, verbose_name='Main Activity')),
                ('startup_options', Tesla.model_fields.EncryptedJSONField(blank=True, default=dict, verbose_name='启动参数')),
                ('auto_install', models.BooleanField(default=False, verbose_name='自动安装')),
                ('replace_install', models.BooleanField(default=True, verbose_name='覆盖安装')),
                ('clear_data', models.BooleanField(default=False, verbose_name='执行前清理数据')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_applications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_applications', to='project.project')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='用例名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('default_timeout', models.PositiveIntegerField(default=10000, verbose_name='默认超时（毫秒）')),
                ('stop_on_failure', models.BooleanField(default=True, verbose_name='失败后停止')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='重试次数')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='case_app.appapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='设备名称')),
                ('udid', models.CharField(max_length=255, verbose_name='设备 UDID')),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=16, verbose_name='平台')),
                ('platform_version', models.CharField(blank=True, default='', max_length=64, verbose_name='系统版本')),
                ('model', models.CharField(blank=True, default='', max_length=128, verbose_name='设备型号')),
                ('resolution', models.CharField(blank=True, default='', max_length=64, verbose_name='分辨率')),
                ('state', models.CharField(choices=[('unknown', '未知'), ('online', '在线'), ('offline', '离线'), ('busy', '占用中')], default='unknown', max_length=16, verbose_name='设备状态')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('last_message', models.CharField(blank=True, default='', max_length=500, verbose_name='最近检测信息')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['state', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='元素名称')),
                ('locator_type', models.CharField(choices=[('accessibility id', 'Accessibility ID'), ('id', 'Resource ID'), ('-android uiautomator', 'UIAutomator'), ('xpath', 'XPath'), ('text', '文本'), ('coordinate', '坐标')], default='id', max_length=32, verbose_name='定位方式')),
                ('locator_value', models.CharField(max_length=1000, verbose_name='定位表达式')),
                ('description', models.CharField(blank=True, default='', max_length=300, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_elements', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_elements', to='project.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_no', models.BigIntegerField(db_index=True, default=case_app.models.generate_execution_no, unique=True)),
                ('status', models.CharField(choices=[('queued', '等待设备'), ('preparing', '准备环境'), ('installing', '安装应用'), ('running', '执行中'), ('reporting', '汇总报告'), ('passed', '通过'), ('failed', '未通过'), ('error', '执行异常'), ('stopped', '已停止')], db_index=True, default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('options', Tesla.model_fields.EncryptedJSONField(blank=True, default=dict)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('log_content', models.TextField(blank=True, default='')),
                ('stop_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='case_app.appapplication')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='case_app.appcase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_runs', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='case_app.appdevice')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_runs', to='project.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
                ('action', models.CharField(choices=[('launch', '启动应用'), ('terminate', '关闭应用'), ('restart', '重启应用'), ('click', '点击'), ('input', '输入文本'), ('clear', '清空输入'), ('swipe', '滑动'), ('back', '返回'), ('home', 'Home'), ('wait', '固定等待'), ('wait_element', '等待元素'), ('get_text', '提取文本'), ('assert_exists', '断言元素存在'), ('assert_text', '断言文本'), ('assert_attribute', '断言属性'), ('screenshot', '截图'), ('set_variable', '设置变量')], max_length=32, verbose_name='操作')),
                ('target', Tesla.model_fields.EncryptedJSONField(blank=True, default=dict, verbose_name='定位/坐标')),
                ('value', Tesla.model_fields.EncryptedTextField(blank=True, default='', verbose_name='操作值')),
                ('options', Tesla.model_fields.EncryptedJSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('continue_on_failure', models.BooleanField(default=False, verbose_name='失败后继续')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='case_app.appcase')),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='case_app.appelement')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=64, verbose_name='版本名称')),
                ('version_code', models.CharField(blank=True, default='', max_length=64, verbose_name='版本号')),
                ('original_name', models.CharField(blank=True, default='', max_length=255, verbose_name='原始文件名')),
                ('file_path', models.CharField(blank=True, default='', max_length=512, verbose_name='安装包路径')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='case_app.appapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_app_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AppStepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('action', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('running', '执行中'), ('passed', '通过'), ('failed', '失败'), ('skipped', '跳过')], max_length=16)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_results', to='case_app.apprun')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='case_app.appstep')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='apprun',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='case_app.appversion'),
        ),
        migrations.CreateModel(
            name='AppExecutionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='节点名称')),
                ('server_url', models.URLField(default='http://127.0.0.1:4723', max_length=255, verbose_name='Appium 地址')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('status', models.CharField(choices=[('unknown', '未知'), ('online', '在线'), ('offline', '离线')], default='unknown', max_length=16, verbose_name='状态')),
                ('last_message', models.CharField(blank=True, default='', max_length=500, verbose_name='最近检测信息')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_nodes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_execution_nodes', to='project.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='appdevice',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='case_app.appexecutionnode'),
        ),
        migrations.AddField(
            model_name='appdevice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_devices', to='project.project'),
        ),
        migrations.AddField(
            model_name='appcase',
            name='default_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_cases', to='case_app.appdevice'),
        ),
        migrations.AddField(
            model_name='appcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_cases', to='project.project'),
        ),
        migrations.CreateModel(
            name='AppArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('screenshot', '截图'), ('page_source', '页面结构'), ('log', '日志')], max_length=24)),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='case_app.apprun')),
                ('step_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='case_app.appstepresult')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='appversion',
            constraint=models.UniqueConstraint(fields=('application', 'version_name'), name='unique_app_version_name'),
        ),
        migrations.AddConstraint(
            model_name='appstep',
            constraint=models.UniqueConstraint(fields=('case', 'order'), name='unique_app_case_step_order'),
        ),
        migrations.AddConstraint(
            model_name='appexecutionnode',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_app_node_name'),
        ),
        migrations.AddConstraint(
            model_name='appelement',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_app_element_name'),
        ),
        migrations.AddConstraint(
            model_name='appdevice',
            constraint=models.UniqueConstraint(fields=('node', 'udid'), name='unique_app_node_device_udid'),
        ),
        migrations.AddConstraint(
            model_name='appcase',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_app_case_name'),
        ),
        migrations.AddConstraint(
            model_name='appapplication',
            constraint=models.UniqueConstraint(fields=('project', 'package_name'), name='unique_project_app_package'),
        ),
    ]
