# Generated by Django 4.2.3 on 2026-09-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0021_environment_browser_token_fields'),
        ('case_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppInspectionSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('remote_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('starting', '启动中'), ('active', '检查中'), ('closed', '已结束'), ('error', '异常')], db_index=True, default='starting', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appelement',
            name='unique_project_app_element_name',
        ),
        migrations.AddField(
            model_name='appelement',
            name='activity',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Activity'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='case_app.appapplication'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='element_class',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='元素类型'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='fallback_locator',
            field=models.JSONField(blank=True, default=list, verbose_name='备用定位'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='页面名称'),
        ),
        migrations.AddField(
            model_name='appelement',
            name='snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='元素快照'),
        ),
        migrations.AlterField(
            model_name='appdevice',
            name='state',
            field=models.CharField(choices=[('unknown', '未知'), ('online', '在线'), ('offline', '离线'), ('busy', '占用中'), ('inspecting', '检查中')], default='unknown', max_length=16, verbose_name='设备状态'),
        ),
        migrations.AddConstraint(
            model_name='appelement',
            constraint=models.UniqueConstraint(fields=('project', 'application', 'name'), name='unique_project_application_app_element_name'),
        ),
        migrations.AddField(
            model_name='appinspectionsession',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='case_app.appapplication'),
        ),
        migrations.AddField(
            model_name='appinspectionsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_inspection_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appinspectionsession',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_sessions', to='case_app.appdevice'),
        ),
        migrations.AddField(
            model_name='appinspectionsession',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_inspection_sessions', to='project.project'),
        ),
        migrations.AddField(
            model_name='appinspectionsession',
            name='version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_sessions', to='case_app.appversion'),
        ),
    ]
