# Generated by Django 4.2.3 on 2026-09-07 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_environment_browser_token_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_app', '0003_inspector_cleanup_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppElementModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='模块名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_modules', to='case_app.appapplication')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_element_modules', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_element_modules', to='project.project')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddField(
            model_name='appelement',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elements', to='case_app.appelementmodule'),
        ),
        migrations.AddConstraint(
            model_name='appelementmodule',
            constraint=models.UniqueConstraint(fields=('application', 'name'), name='unique_app_element_module_name'),
        ),
    ]
