# Generated by Django 4.2.3 on 2026-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0004_appelementmodule_appelement_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appelement',
            name='locator_type',
            field=models.CharField(choices=[('accessibility id', 'Accessibility ID'), ('id', 'Resource ID'), ('-android uiautomator', 'UIAutomator'), ('xpath', 'XPath'), ('text', '文本'), ('coordinate', '坐标'), ('ocr_text', 'OCR 文字'), ('image_text', '图像文字')], default='id', max_length=32, verbose_name='定位方式'),
        ),
    ]
