# Generated by Django 4.2.3 on 2026-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0005_alter_appelement_locator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstepresult',
            name='detail',
            field=models.JSONField(blank=True, default=dict, verbose_name='执行快照'),
        ),
    ]
