# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_app_tenants(apps, schema_editor):
    for model_name in ('AppCase', 'AppRun'):
        Model = apps.get_model('case_app', model_name)
        for item in Model.objects.select_related('project').iterator():
            if item.tenant_id != item.project.tenant_id:
                Model.objects.filter(pk=item.pk).update(tenant_id=item.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('case_app', '0007_appcase_environment_name'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appcase',
            name='unique_project_app_case_name',
        ),
        migrations.AddField(
            model_name='appcase',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='app_cases', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='apprun',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='app_runs', to='account.tenant'),
        ),
        migrations.RunPython(backfill_app_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='appcase',
            index=models.Index(fields=['tenant', 'project', 'updated_at'], name='app_case_tenant_project_idx'),
        ),
        migrations.AddIndex(
            model_name='apprun',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='app_run_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='appcase',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'name'), name='unique_tenant_app_case_name'),
        ),
    ]
