# Generated by Django 4.2.3 on 2023-08-15 21:39

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="head_img",
            field=models.FileField(
                upload_to=account.models.user_head_img_path, verbose_name="头像地址"
            ),
        ),
    ]
