# Generated by Django 4.2.3 on 2023-09-14 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_alter_profile_head_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="head_img",
            field=models.CharField(max_length=512, verbose_name="头像地址"),
        ),
        migrations.CreateModel(
            name="HeadImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.FileField(
                        upload_to=account.models.user_head_img_path, verbose_name="头像地址"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
