# Generated by Django 4.2.3 on 2026-08-08 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_profile_head_img_headimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HeadImage',
        ),
    ]
