# Generated by Django 4.2.3 on 2026-08-08 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_headimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='head_img',
        ),
    ]
