# Generated by Django 4.2.3 on 2026-08-09
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("account", "0006_alter_profile_name")]

    operations = [migrations.RemoveField(model_name="profile", name="name")]
