/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/account/profile/all_user/': {
    /** @description 查询多个数据，返回多个数据 */
    get: operations['account_profile_all_user_retrieve'];
  };
  '/api/account/profile/change/': {
    post: operations['account_profile_change_create'];
  };
  '/api/account/profile/img_upload/': {
    post: operations['account_profile_img_upload_create'];
  };
  '/api/account/profile/login/': {
    post: operations['account_profile_login_create'];
  };
  '/api/account/profile/profile/': {
    /** @description 查询单个数，返回单个数据 */
    get: operations['account_profile_profile_retrieve'];
  };
  '/api/account/profile/reset_password/': {
    post: operations['account_profile_reset_password_create'];
  };
  '/api/case_api/endpoint/': {
    get: operations['case_api_endpoint_list'];
    post: operations['case_api_endpoint_create'];
  };
  '/api/case_api/endpoint/{id}/': {
    get: operations['case_api_endpoint_retrieve'];
    put: operations['case_api_endpoint_update'];
    delete: operations['case_api_endpoint_destroy'];
    patch: operations['case_api_endpoint_partial_update'];
  };
  '/api/case_api/scenario/': {
    get: operations['case_api_scenario_list'];
    post: operations['case_api_scenario_create'];
  };
  '/api/case_api/scenario-step/': {
    get: operations['case_api_scenario_step_list'];
    post: operations['case_api_scenario_step_create'];
  };
  '/api/case_api/scenario-step/{id}/': {
    get: operations['case_api_scenario_step_retrieve'];
    put: operations['case_api_scenario_step_update'];
    delete: operations['case_api_scenario_step_destroy'];
    patch: operations['case_api_scenario_step_partial_update'];
  };
  '/api/case_api/scenario/{id}/': {
    get: operations['case_api_scenario_retrieve'];
    put: operations['case_api_scenario_update'];
    delete: operations['case_api_scenario_destroy'];
    patch: operations['case_api_scenario_partial_update'];
  };
  '/api/case_ui/element/': {
    get: operations['case_ui_element_list'];
    post: operations['case_ui_element_create'];
  };
  '/api/case_ui/element/{id}/': {
    get: operations['case_ui_element_retrieve'];
    put: operations['case_ui_element_update'];
    delete: operations['case_ui_element_destroy'];
    patch: operations['case_ui_element_partial_update'];
  };
  '/api/project/environment/': {
    get: operations['project_environment_list'];
    post: operations['project_environment_create'];
  };
  '/api/project/environment/{id}/': {
    get: operations['project_environment_retrieve'];
    put: operations['project_environment_update'];
    delete: operations['project_environment_destroy'];
    patch: operations['project_environment_partial_update'];
  };
  '/api/project/project/': {
    get: operations['project_project_list'];
    post: operations['project_project_create'];
  };
  '/api/project/project/{id}/': {
    get: operations['project_project_retrieve'];
    put: operations['project_project_update'];
    delete: operations['project_project_destroy'];
    patch: operations['project_project_partial_update'];
  };
  '/api/schema/openapi.json': {
    /**
     * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
     *
     * - YAML: application/vnd.oai.openapi
     * - JSON: application/vnd.oai.openapi+json
     */
    get: operations['schema_openapi.json_retrieve'];
  };
  '/api/suite/run_result/': {
    get: operations['suite_run_result_list'];
  };
  '/api/suite/run_result/{id}/': {
    get: operations['suite_run_result_retrieve'];
  };
  '/api/suite/scenario/': {
    get: operations['suite_scenario_list'];
    post: operations['suite_scenario_create'];
  };
  '/api/suite/scenario/{id}/': {
    get: operations['suite_scenario_retrieve'];
    put: operations['suite_scenario_update'];
    delete: operations['suite_scenario_destroy'];
    patch: operations['suite_scenario_partial_update'];
  };
  '/api/suite/static/{path}': {
    get: operations['suite_static_retrieve'];
  };
  '/api/suite/suite/': {
    get: operations['suite_suite_list'];
    post: operations['suite_suite_create'];
  };
  '/api/suite/suite/{id}/': {
    get: operations['suite_suite_retrieve'];
    put: operations['suite_suite_update'];
    delete: operations['suite_suite_destroy'];
    patch: operations['suite_suite_partial_update'];
  };
  '/api/suite/suite/{id}/run/': {
    /** @description 执行测试套件 */
    post: operations['suite_suite_run_create'];
  };
  '/api/suite/suite/{id}/webhook/': {
    /** @description 执行测试套件 */
    get: operations['suite_suite_webhook_retrieve'];
    /** @description 执行测试套件 */
    post: operations['suite_suite_webhook_create'];
  };
  '/api/system/department/': {
    get: operations['system_department_list'];
    post: operations['system_department_create'];
  };
  '/api/system/department/{id}/': {
    get: operations['system_department_retrieve'];
    put: operations['system_department_update'];
    delete: operations['system_department_destroy'];
    patch: operations['system_department_partial_update'];
  };
  '/api/system/position/': {
    get: operations['system_position_list'];
    post: operations['system_position_create'];
  };
  '/api/system/position/{id}/': {
    get: operations['system_position_retrieve'];
    put: operations['system_position_update'];
    delete: operations['system_position_destroy'];
    patch: operations['system_position_partial_update'];
  };
  '/api/system/role/': {
    get: operations['system_role_list'];
    post: operations['system_role_create'];
  };
  '/api/system/role/{id}/': {
    get: operations['system_role_retrieve'];
    put: operations['system_role_update'];
    delete: operations['system_role_destroy'];
    patch: operations['system_role_partial_update'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * @description * `CLASS_NAME` - CLASS_NAME
     * * `CSS_SELECTOR` - CSS_SELECTOR
     * * `ID` - ID
     * * `LINK_TEXT` - LINK_TEXT
     * * `NAME` - NAME
     * * `PARTIAL_LINK_TEXT` - PARTIAL_LINK_TEXT
     * * `TAG_NAME` - TAG_NAME
     * * `XPATH` - XPATH
     * @enum {string}
     */
    ByEnum:
      | 'CLASS_NAME'
      | 'CSS_SELECTOR'
      | 'ID'
      | 'LINK_TEXT'
      | 'NAME'
      | 'PARTIAL_LINK_TEXT'
      | 'TAG_NAME'
      | 'XPATH';
    Department: {
      id: number;
      leader_img: string;
      leader_name: string;
      /** 部门名称 */
      name: string;
      /** 部门简介 */
      intro?: string;
      leader?: number | null;
    };
    Element: {
      id: number;
      project_info: components['schemas']['Project'];
      /** 元素名称 */
      name: string;
      /** 定位方式 */
      by?: components['schemas']['ByEnum'];
      /** 定位表达式 */
      value: string;
      project: number;
    };
    Endpoint: {
      id: number;
      project_name: string;
      /** 接口名称 */
      name: string;
      /** 请求方法 */
      method: string;
      /** 接口地址 */
      url: string;
      /** 查询字符串 */
      params?: {
        [key: string]: unknown;
      } | null;
      /** 表单参数 */
      data?: {
        [key: string]: unknown;
      } | null;
      /** JSON参数 */
      json?: {
        [key: string]: unknown;
      } | null;
      cookies?: {
        [key: string]: unknown;
      } | null;
      /** 请求头 */
      headers?: {
        [key: string]: unknown;
      } | null;
      project: number;
    };
    Environment: {
      id: number;
      project_name: string;
      /** 环境名称 */
      name: string;
      /** 环境地址 */
      base_url: string;
      /** 启用自动登录 */
      auth_enabled?: boolean;
      /** 登录接口 */
      login_url?: string;
      /** 登录方法 */
      login_method?: string;
      /** 登录请求头 */
      login_headers?: {
        [key: string]: unknown;
      };
      /** 登录查询参数 */
      login_params?: {
        [key: string]: unknown;
      };
      /** 登录表单参数 */
      login_data?: {
        [key: string]: unknown;
      };
      /** 登录 JSON 参数 */
      login_json?: {
        [key: string]: unknown;
      };
      /** Token 提取表达式 */
      token_jsonpath?: string;
      /** 变量名 */
      token_name?: string;
      /** Token 请求头 */
      token_header?: string;
      /** Token 前缀 */
      token_prefix?: string;
      project: number;
    };
    HeadImage: {
      id: number;
      user: string;
      /**
       * 头像地址
       * Format: uri
       */
      img: string;
    };
    Login: {
      username: string;
      password: string;
    };
    PaginatedDepartmentList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Department'][];
    };
    PaginatedElementList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Element'][];
    };
    PaginatedEndpointList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Endpoint'][];
    };
    PaginatedEnvironmentList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Environment'][];
    };
    PaginatedPositionList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Position'][];
    };
    PaginatedProjectList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Project'][];
    };
    PaginatedRoleShowList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['RoleShow'][];
    };
    PaginatedRunResultList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['RunResult'][];
    };
    PaginatedScenarioList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Scenario'][];
    };
    PaginatedScenarioStepList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['ScenarioStep'][];
    };
    PaginatedSuiteList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['Suite'][];
    };
    PaginatedSuiteScenarioList: {
      /** @example 123 */
      count?: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results?: components['schemas']['SuiteScenario'][];
    };
    PatchedDepartment: {
      id?: number;
      leader_img?: string;
      leader_name?: string;
      /** 部门名称 */
      name?: string;
      /** 部门简介 */
      intro?: string;
      leader?: number | null;
    };
    PatchedElement: {
      id?: number;
      project_info?: components['schemas']['Project'];
      /** 元素名称 */
      name?: string;
      /** 定位方式 */
      by?: components['schemas']['ByEnum'];
      /** 定位表达式 */
      value?: string;
      project?: number;
    };
    PatchedEndpoint: {
      id?: number;
      project_name?: string;
      /** 接口名称 */
      name?: string;
      /** 请求方法 */
      method?: string;
      /** 接口地址 */
      url?: string;
      /** 查询字符串 */
      params?: {
        [key: string]: unknown;
      } | null;
      /** 表单参数 */
      data?: {
        [key: string]: unknown;
      } | null;
      /** JSON参数 */
      json?: {
        [key: string]: unknown;
      } | null;
      cookies?: {
        [key: string]: unknown;
      } | null;
      /** 请求头 */
      headers?: {
        [key: string]: unknown;
      } | null;
      project?: number;
    };
    PatchedEnvironment: {
      id?: number;
      project_name?: string;
      /** 环境名称 */
      name?: string;
      /** 环境地址 */
      base_url?: string;
      /** 启用自动登录 */
      auth_enabled?: boolean;
      /** 登录接口 */
      login_url?: string;
      /** 登录方法 */
      login_method?: string;
      /** 登录请求头 */
      login_headers?: {
        [key: string]: unknown;
      };
      /** 登录查询参数 */
      login_params?: {
        [key: string]: unknown;
      };
      /** 登录表单参数 */
      login_data?: {
        [key: string]: unknown;
      };
      /** 登录 JSON 参数 */
      login_json?: {
        [key: string]: unknown;
      };
      /** Token 提取表达式 */
      token_jsonpath?: string;
      /** 变量名 */
      token_name?: string;
      /** Token 请求头 */
      token_header?: string;
      /** Token 前缀 */
      token_prefix?: string;
      project?: number;
    };
    PatchedPosition: {
      id?: number;
      /** 职位名称 */
      name?: string;
      /** 负责人 */
      is_leader?: boolean;
    };
    PatchedProject: {
      id?: number;
      pm_profile?: string;
      /** 项目名称 */
      name?: string;
      /** 项目简介 */
      intro?: string;
      pm?: number | null;
      user_list?: number[];
    };
    PatchedRole: {
      id?: number;
      user?: number;
      department?: number;
      position?: number;
    };
    PatchedScenario: {
      id?: number;
      project_name?: string;
      step_count?: number;
      /** 场景名称 */
      name?: string;
      /** 场景描述 */
      description?: string;
      project?: number;
    };
    PatchedScenarioStep: {
      id?: number;
      endpoint_name?: string;
      endpoint_info?: components['schemas']['Endpoint'];
      /** 步骤名称 */
      name?: string;
      /** 执行顺序 */
      order?: number;
      /** 参数覆盖 */
      request_override?: {
        [key: string]: unknown;
      };
      /** 数据提取 */
      extract?: {
        [key: string]: unknown;
      };
      /** 断言 */
      validate?: {
        [key: string]: unknown;
      };
      /** 失败后继续 */
      continue_on_failure?: boolean;
      scenario?: number;
      endpoint?: number | null;
    };
    PatchedSuite: {
      id?: number;
      case_api_count?: number;
      run_type_display?: string;
      schedule?: number | null;
      environment_name?: string;
      /** 套件名称 */
      name?: string;
      /** 套件描述 */
      description?: string;
      /** 运行类型 */
      run_type?: components['schemas']['RunTypeEnum'];
      /** Cron表达式 */
      cron?: string;
      /** Hook密钥 */
      hook_key?: string;
      /** 执行环境 */
      environment?: number | null;
      scenarios?: readonly number[];
    };
    PatchedSuiteScenario: {
      id?: number;
      scenario_name?: string;
      /** 执行顺序 */
      order?: number;
      /** 失败后继续下一场景 */
      continue_on_failure?: boolean;
      suite?: number;
      scenario?: number;
    };
    Position: {
      id: number;
      /** 职位名称 */
      name: string;
      /** 负责人 */
      is_leader?: boolean;
    };
    Profile: {
      id: number;
      token: string;
      user: string;
      role_list: readonly components['schemas']['RoleShow'][];
      /** 昵称 */
      name: string;
      /** 头像地址 */
      head_img: string;
    };
    Project: {
      id: number;
      /** 项目名称 */
      name: string;
      /** 项目简介 */
      intro?: string;
      pm?: number | null;
      user_list?: number[];
    };
    ResetPass: {
      new_password: string;
      confirm_password: string;
    };
    Role: {
      id: number;
      user: number;
      department: number;
      position: number;
    };
    RoleShow: {
      department: string;
      position: string;
      is_leader: boolean;
    };
    RunResult: {
      id: number;
      project_name: string;
      suite_name: string;
      run_type: string;
      status: string;
      log_url: string;
      artifacts_url: string;
      /** 测试通过 */
      is_pass?: boolean;
      /**
       * 创建时间
       * Format: date-time
       */
      create_datetime: string;
      /**
       * 更新时间
       * Format: date-time
       */
      update_datetime: string;
      suite: number;
      project: number;
    };
    /**
     * @description * `O` - 单次执行
     * * `C` - Cron
     * * `W` - WebHook
     * @enum {string}
     */
    RunTypeEnum: 'O' | 'C' | 'W';
    Scenario: {
      id: number;
      project_name: string;
      step_count: number;
      /** 场景名称 */
      name: string;
      /** 场景描述 */
      description?: string;
      project: number;
    };
    ScenarioStep: {
      id: number;
      endpoint_name: string;
      endpoint_info: components['schemas']['Endpoint'];
      /** 步骤名称 */
      name?: string;
      /** 执行顺序 */
      order?: number;
      /** 参数覆盖 */
      request_override?: {
        [key: string]: unknown;
      };
      /** 数据提取 */
      extract?: {
        [key: string]: unknown;
      };
      /** 断言 */
      validate?: {
        [key: string]: unknown;
      };
      /** 失败后继续 */
      continue_on_failure?: boolean;
      scenario: number;
      endpoint?: number | null;
    };
    Suite: {
      id: number;
      case_api_count: number;
      run_type_display: string;
      schedule: number | null;
      environment_name: string;
      /** 套件名称 */
      name: string;
      /** 套件描述 */
      description?: string;
      /** 运行类型 */
      run_type?: components['schemas']['RunTypeEnum'];
      /** Cron表达式 */
      cron?: string;
      /** Hook密钥 */
      hook_key?: string;
      /** 执行环境 */
      environment?: number | null;
      scenarios: readonly number[];
    };
    SuiteScenario: {
      id: number;
      scenario_name: string;
      /** 执行顺序 */
      order?: number;
      /** 失败后继续下一场景 */
      continue_on_failure?: boolean;
      suite: number;
      scenario: number;
    };
    UserList: {
      id: number;
      /** 昵称 */
      name: string;
      /** 头像地址 */
      head_img: string;
      user: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** @description 查询多个数据，返回多个数据 */
  account_profile_all_user_retrieve: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['UserList'];
        };
      };
    };
  };
  account_profile_change_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Profile'];
        'application/x-www-form-urlencoded': components['schemas']['Profile'];
        'multipart/form-data': components['schemas']['Profile'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  account_profile_img_upload_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['HeadImage'];
        'application/x-www-form-urlencoded': components['schemas']['HeadImage'];
        'multipart/form-data': components['schemas']['HeadImage'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['HeadImage'];
        };
      };
    };
  };
  account_profile_login_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Login'];
        'application/x-www-form-urlencoded': components['schemas']['Login'];
        'multipart/form-data': components['schemas']['Login'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  /** @description 查询单个数，返回单个数据 */
  account_profile_profile_retrieve: {
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Profile'];
        };
      };
    };
  };
  account_profile_reset_password_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['ResetPass'];
        'application/x-www-form-urlencoded': components['schemas']['ResetPass'];
        'multipart/form-data': components['schemas']['ResetPass'];
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  case_api_endpoint_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedEndpointList'];
        };
      };
    };
  };
  case_api_endpoint_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Endpoint'];
        'application/x-www-form-urlencoded': components['schemas']['Endpoint'];
        'multipart/form-data': components['schemas']['Endpoint'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  case_api_endpoint_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  case_api_endpoint_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Endpoint'];
        'application/x-www-form-urlencoded': components['schemas']['Endpoint'];
        'multipart/form-data': components['schemas']['Endpoint'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  case_api_endpoint_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  case_api_endpoint_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this endpoint. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedEndpoint'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedEndpoint'];
        'multipart/form-data': components['schemas']['PatchedEndpoint'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Endpoint'];
        };
      };
    };
  };
  case_api_scenario_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedScenarioList'];
        };
      };
    };
  };
  case_api_scenario_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Scenario'];
        'application/x-www-form-urlencoded': components['schemas']['Scenario'];
        'multipart/form-data': components['schemas']['Scenario'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Scenario'];
        };
      };
    };
  };
  case_api_scenario_step_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedScenarioStepList'];
        };
      };
    };
  };
  case_api_scenario_step_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['ScenarioStep'];
        'application/x-www-form-urlencoded': components['schemas']['ScenarioStep'];
        'multipart/form-data': components['schemas']['ScenarioStep'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['ScenarioStep'];
        };
      };
    };
  };
  case_api_scenario_step_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario step. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ScenarioStep'];
        };
      };
    };
  };
  case_api_scenario_step_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario step. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScenarioStep'];
        'application/x-www-form-urlencoded': components['schemas']['ScenarioStep'];
        'multipart/form-data': components['schemas']['ScenarioStep'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ScenarioStep'];
        };
      };
    };
  };
  case_api_scenario_step_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario step. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  case_api_scenario_step_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario step. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedScenarioStep'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedScenarioStep'];
        'multipart/form-data': components['schemas']['PatchedScenarioStep'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['ScenarioStep'];
        };
      };
    };
  };
  case_api_scenario_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Scenario'];
        };
      };
    };
  };
  case_api_scenario_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Scenario'];
        'application/x-www-form-urlencoded': components['schemas']['Scenario'];
        'multipart/form-data': components['schemas']['Scenario'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Scenario'];
        };
      };
    };
  };
  case_api_scenario_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  case_api_scenario_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this scenario. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedScenario'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedScenario'];
        'multipart/form-data': components['schemas']['PatchedScenario'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Scenario'];
        };
      };
    };
  };
  case_ui_element_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedElementList'];
        };
      };
    };
  };
  case_ui_element_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Element'];
        'application/x-www-form-urlencoded': components['schemas']['Element'];
        'multipart/form-data': components['schemas']['Element'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  case_ui_element_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  case_ui_element_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Element'];
        'application/x-www-form-urlencoded': components['schemas']['Element'];
        'multipart/form-data': components['schemas']['Element'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  case_ui_element_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  case_ui_element_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this element. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedElement'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedElement'];
        'multipart/form-data': components['schemas']['PatchedElement'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Element'];
        };
      };
    };
  };
  project_environment_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedEnvironmentList'];
        };
      };
    };
  };
  project_environment_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Environment'];
        'application/x-www-form-urlencoded': components['schemas']['Environment'];
        'multipart/form-data': components['schemas']['Environment'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
    };
  };
  project_environment_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this environment. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
    };
  };
  project_environment_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this environment. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Environment'];
        'application/x-www-form-urlencoded': components['schemas']['Environment'];
        'multipart/form-data': components['schemas']['Environment'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
    };
  };
  project_environment_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this environment. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  project_environment_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this environment. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedEnvironment'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedEnvironment'];
        'multipart/form-data': components['schemas']['PatchedEnvironment'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Environment'];
        };
      };
    };
  };
  project_project_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedProjectList'];
        };
      };
    };
  };
  project_project_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
        'application/x-www-form-urlencoded': components['schemas']['Project'];
        'multipart/form-data': components['schemas']['Project'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  project_project_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  project_project_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Project'];
        'application/x-www-form-urlencoded': components['schemas']['Project'];
        'multipart/form-data': components['schemas']['Project'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  project_project_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  project_project_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this project. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedProject'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedProject'];
        'multipart/form-data': components['schemas']['PatchedProject'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Project'];
        };
      };
    };
  };
  /**
   * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
   *
   * - YAML: application/vnd.oai.openapi
   * - JSON: application/vnd.oai.openapi+json
   */
  'schema_openapi.json_retrieve': {
    parameters: {
      query?: {
        format?: 'json' | 'yaml';
        lang?:
          | 'af'
          | 'ar'
          | 'ar-dz'
          | 'ast'
          | 'az'
          | 'be'
          | 'bg'
          | 'bn'
          | 'br'
          | 'bs'
          | 'ca'
          | 'ckb'
          | 'cs'
          | 'cy'
          | 'da'
          | 'de'
          | 'dsb'
          | 'el'
          | 'en'
          | 'en-au'
          | 'en-gb'
          | 'eo'
          | 'es'
          | 'es-ar'
          | 'es-co'
          | 'es-mx'
          | 'es-ni'
          | 'es-ve'
          | 'et'
          | 'eu'
          | 'fa'
          | 'fi'
          | 'fr'
          | 'fy'
          | 'ga'
          | 'gd'
          | 'gl'
          | 'he'
          | 'hi'
          | 'hr'
          | 'hsb'
          | 'hu'
          | 'hy'
          | 'ia'
          | 'id'
          | 'ig'
          | 'io'
          | 'is'
          | 'it'
          | 'ja'
          | 'ka'
          | 'kab'
          | 'kk'
          | 'km'
          | 'kn'
          | 'ko'
          | 'ky'
          | 'lb'
          | 'lt'
          | 'lv'
          | 'mk'
          | 'ml'
          | 'mn'
          | 'mr'
          | 'ms'
          | 'my'
          | 'nb'
          | 'ne'
          | 'nl'
          | 'nn'
          | 'os'
          | 'pa'
          | 'pl'
          | 'pt'
          | 'pt-br'
          | 'ro'
          | 'ru'
          | 'sk'
          | 'sl'
          | 'sq'
          | 'sr'
          | 'sr-latn'
          | 'sv'
          | 'sw'
          | 'ta'
          | 'te'
          | 'tg'
          | 'th'
          | 'tk'
          | 'tr'
          | 'tt'
          | 'udm'
          | 'uk'
          | 'ur'
          | 'uz'
          | 'vi'
          | 'zh-hans'
          | 'zh-hant';
      };
    };
    responses: {
      200: {
        content: {
          'application/vnd.oai.openapi': {
            [key: string]: unknown;
          };
          'application/yaml': {
            [key: string]: unknown;
          };
          'application/vnd.oai.openapi+json': {
            [key: string]: unknown;
          };
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  suite_run_result_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedRunResultList'];
        };
      };
    };
  };
  suite_run_result_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this run result. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['RunResult'];
        };
      };
    };
  };
  suite_scenario_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedSuiteScenarioList'];
        };
      };
    };
  };
  suite_scenario_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['SuiteScenario'];
        'application/x-www-form-urlencoded': components['schemas']['SuiteScenario'];
        'multipart/form-data': components['schemas']['SuiteScenario'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['SuiteScenario'];
        };
      };
    };
  };
  suite_scenario_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite scenario. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['SuiteScenario'];
        };
      };
    };
  };
  suite_scenario_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite scenario. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SuiteScenario'];
        'application/x-www-form-urlencoded': components['schemas']['SuiteScenario'];
        'multipart/form-data': components['schemas']['SuiteScenario'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['SuiteScenario'];
        };
      };
    };
  };
  suite_scenario_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite scenario. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  suite_scenario_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite scenario. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedSuiteScenario'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedSuiteScenario'];
        'multipart/form-data': components['schemas']['PatchedSuiteScenario'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['SuiteScenario'];
        };
      };
    };
  };
  suite_static_retrieve: {
    parameters: {
      path: {
        path: string;
      };
    };
    responses: {
      /** @description No response body */
      200: {
        content: never;
      };
    };
  };
  suite_suite_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedSuiteList'];
        };
      };
    };
  };
  suite_suite_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  suite_suite_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  suite_suite_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  suite_suite_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  suite_suite_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedSuite'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedSuite'];
        'multipart/form-data': components['schemas']['PatchedSuite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  suite_suite_run_create: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  suite_suite_webhook_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  /** @description 执行测试套件 */
  suite_suite_webhook_create: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this suite. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Suite'];
        'application/x-www-form-urlencoded': components['schemas']['Suite'];
        'multipart/form-data': components['schemas']['Suite'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Suite'];
        };
      };
    };
  };
  system_department_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedDepartmentList'];
        };
      };
    };
  };
  system_department_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Department'];
        'application/x-www-form-urlencoded': components['schemas']['Department'];
        'multipart/form-data': components['schemas']['Department'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  system_department_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  system_department_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Department'];
        'application/x-www-form-urlencoded': components['schemas']['Department'];
        'multipart/form-data': components['schemas']['Department'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  system_department_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  system_department_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this department. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedDepartment'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedDepartment'];
        'multipart/form-data': components['schemas']['PatchedDepartment'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Department'];
        };
      };
    };
  };
  system_position_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedPositionList'];
        };
      };
    };
  };
  system_position_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Position'];
        'application/x-www-form-urlencoded': components['schemas']['Position'];
        'multipart/form-data': components['schemas']['Position'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  system_position_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  system_position_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Position'];
        'application/x-www-form-urlencoded': components['schemas']['Position'];
        'multipart/form-data': components['schemas']['Position'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  system_position_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  system_position_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this position. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedPosition'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedPosition'];
        'multipart/form-data': components['schemas']['PatchedPosition'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Position'];
        };
      };
    };
  };
  system_role_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        pageSize?: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['PaginatedRoleShowList'];
        };
      };
    };
  };
  system_role_create: {
    requestBody: {
      content: {
        'application/json': components['schemas']['Role'];
        'application/x-www-form-urlencoded': components['schemas']['Role'];
        'multipart/form-data': components['schemas']['Role'];
      };
    };
    responses: {
      201: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  system_role_retrieve: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  system_role_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['Role'];
        'application/x-www-form-urlencoded': components['schemas']['Role'];
        'multipart/form-data': components['schemas']['Role'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
  system_role_destroy: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    responses: {
      /** @description No response body */
      204: {
        content: never;
      };
    };
  };
  system_role_partial_update: {
    parameters: {
      path: {
        /** @description A unique integer value identifying this role. */
        id: number;
      };
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['PatchedRole'];
        'application/x-www-form-urlencoded': components['schemas']['PatchedRole'];
        'multipart/form-data': components['schemas']['PatchedRole'];
      };
    };
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['Role'];
        };
      };
    };
  };
}
