# Generated by Django 4.2.3 on 2026-09-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0021_environment_browser_token_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=160, unique=True, verbose_name='实例标识')),
                ('name', models.CharField(max_length=160, verbose_name='执行器名称')),
                ('kind', models.CharField(choices=[('scheduler', 'API/UI/App 执行器'), ('performance', '性能执行器')], db_index=True, max_length=20, verbose_name='执行器类型')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('process_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='进程 ID')),
                ('status', models.CharField(choices=[('online', '在线'), ('degraded', '异常'), ('offline', '离线')], db_index=True, default='online', max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='并发容量')),
                ('active_tasks', models.PositiveSmallIntegerField(default=0, verbose_name='活动任务')),
                ('capabilities', models.JSONField(blank=True, default=list, verbose_name='能力')),
                ('version', models.CharField(blank=True, default='', max_length=64, verbose_name='版本')),
                ('message', models.CharField(blank=True, default='', max_length=500, verbose_name='状态说明')),
                ('started_at', models.DateTimeField(verbose_name='启动时间')),
                ('last_heartbeat_at', models.DateTimeField(db_index=True, verbose_name='最近心跳')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kind', 'name', 'instance_id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('suite', '测试计划'), ('app', 'App 测试'), ('performance', '性能测试')], db_index=True, max_length=20, verbose_name='任务类型')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='源任务 ID')),
                ('execution_no', models.CharField(db_index=True, max_length=32, verbose_name='执行编号')),
                ('name', models.CharField(max_length=160, verbose_name='任务名称')),
                ('engine', models.CharField(max_length=32, verbose_name='执行引擎')),
                ('status', models.CharField(choices=[('queued', '等待调度'), ('preparing', '准备环境'), ('running', '执行中'), ('paused', '已暂停'), ('reporting', '汇总报告'), ('succeeded', '执行成功'), ('failed', '执行失败'), ('error', '执行异常'), ('canceled', '已取消'), ('stopped', '已停止')], db_index=True, max_length=20)),
                ('raw_status', models.CharField(blank=True, default='', max_length=32, verbose_name='原始状态')),
                ('stage', models.CharField(blank=True, default='', max_length=64, verbose_name='当前阶段')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度')),
                ('diagnostic_code', models.CharField(blank=True, default='', max_length=64, verbose_name='诊断编码')),
                ('diagnostic_message', models.TextField(blank=True, default='', verbose_name='诊断信息')),
                ('recovery_count', models.PositiveSmallIntegerField(default=0, verbose_name='恢复次数')),
                ('last_recovered_at', models.DateTimeField(blank=True, null=True, verbose_name='最近恢复时间')),
                ('timeout_seconds', models.PositiveIntegerField(default=1800, verbose_name='超时秒数')),
                ('last_activity_at', models.DateTimeField(db_index=True, verbose_name='最近活动')),
                ('queued_at', models.DateTimeField(verbose_name='入队时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('source_created_at', models.DateTimeField(verbose_name='源任务创建时间')),
                ('source_updated_at', models.DateTimeField(verbose_name='源任务更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execution_control_tasks', to='project.project')),
            ],
            options={
                'ordering': ['-source_created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'last_activity_at'], name='exec_task_status_activity_idx'), models.Index(fields=['project', 'source_created_at'], name='exec_task_project_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='executiontask',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_id'), name='unique_execution_control_source'),
        ),
    ]
