# Generated by Django 4.2.3 on 2026-09-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='dispatch_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='派发次数'),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='派发时间'),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='resource_keys',
            field=models.JSONField(blank=True, default=list, verbose_name='所需资源'),
        ),
        migrations.AddField(
            model_name='executiontask',
            name='waiting_reason',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='排队原因'),
        ),
    ]
