# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_execution_task_tenants(apps, schema_editor):
    Task = apps.get_model('execution_control', 'ExecutionTask')
    for task in Task.objects.select_related('project').iterator():
        if task.project_id and task.tenant_id != task.project.tenant_id:
            Task.objects.filter(pk=task.pk).update(tenant_id=task.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('execution_control', '0002_executiontask_dispatch_attempts_and_more'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='executiontask',
            name='unique_execution_control_source',
        ),
        migrations.AddField(
            model_name='executiontask',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='execution_tasks', to='account.tenant'),
        ),
        migrations.RunPython(backfill_execution_task_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='executiontask',
            index=models.Index(fields=['tenant', 'status', 'last_activity_at'], name='exec_task_tenant_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='executiontask',
            constraint=models.UniqueConstraint(fields=('tenant', 'source_type', 'source_id'), name='unique_tenant_execution_control_source'),
        ),
    ]
