# Generated by Django 4.2.3 on 2026-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution_control', '0004_executiontask_effective_start_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontask',
            name='executor_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='执行人'),
        ),
    ]
