# Generated by Django 4.2.7 on 2026-08-29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("system", "0002_remove_department_position_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True, verbose_name="连接名称")),
                ("host", models.CharField(max_length=255, verbose_name="服务器地址")),
                ("port", models.PositiveIntegerField(default=22, verbose_name="SSH 端口")),
                ("username", models.CharField(max_length=128, verbose_name="登录账号")),
                ("auth_type", models.CharField(choices=[("private_key", "私钥认证"), ("password", "密码认证")], default="private_key", max_length=16, verbose_name="认证方式")),
                ("private_key_path", models.CharField(blank=True, max_length=512, verbose_name="服务器可访问的私钥路径")),
                ("private_key_passphrase", models.CharField(blank=True, max_length=512, verbose_name="私钥口令")),
                ("password", models.CharField(blank=True, max_length=512, verbose_name="登录密码")),
                ("strict_host_key", models.BooleanField(default=True, verbose_name="校验主机指纹")),
                ("enabled", models.BooleanField(default=True, verbose_name="启用")),
                ("description", models.CharField(blank=True, max_length=256, verbose_name="备注")),
                ("last_tested_at", models.DateTimeField(blank=True, null=True, verbose_name="最近测试时间")),
                ("last_test_status", models.BooleanField(blank=True, null=True, verbose_name="最近测试成功")),
                ("last_test_message", models.CharField(blank=True, max_length=512, verbose_name="最近测试信息")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="created_server_connections", to=settings.AUTH_USER_MODEL, verbose_name="创建人")),
            ],
            options={"ordering": ["-updated_at", "-id"]},
        ),
    ]
