# Generated by Django 4.2.3 on 2026-09-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to='system/branding/', verbose_name='浏览器 Tab 图标'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='platform_icon',
            field=models.FileField(blank=True, null=True, upload_to='system/branding/', verbose_name='平台左上角图标'),
        ),
    ]
