# Generated by Django 4.2.3 on 2026-09-08 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_systemconfiguration_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfiguration',
            name='favicon',
        ),
    ]
