# Generated by Django 4.2.3 on 2026-09-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_remove_systemconfiguration_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfiguration',
            name='platform_icon',
            field=models.FileField(blank=True, null=True, upload_to='system/branding/', verbose_name='平台图标'),
        ),
    ]
