# Generated by Django 4.2.3 on 2026-09-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_systemconfiguration_platform_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_worker_count',
            field=models.PositiveSmallIntegerField(default=2, help_text='API、UI 和 App 任务共用的平台最大并发 Worker 数。', verbose_name='最大 Worker 数'),
        ),
    ]
