# Generated by Django 4.2.3 on 2026-09-13 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_systemconfiguration_max_worker_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='max_performance_worker_count',
            field=models.PositiveSmallIntegerField(default=1, help_text='性能测试任务可同时启动的 k6 工作进程数。', verbose_name='最大性能 Worker 数'),
        ),
    ]
