# Generated by Django 4.2.3 on 2026-09-14 11:10

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_server_tenants(apps, schema_editor):
    ServerConnection = apps.get_model('system', 'ServerConnection')
    for connection in ServerConnection.objects.select_related('project').iterator():
        if connection.project_id and connection.tenant_id != connection.project.tenant_id:
            ServerConnection.objects.filter(pk=connection.pk).update(
                tenant_id=connection.project.tenant_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_tenant_max_performance_worker_count'),
        ('system', '0011_systemconfiguration_max_performance_worker_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconnection',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='server_connections', to='account.tenant', verbose_name='所属租户'),
        ),
        migrations.RunPython(backfill_server_tenants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='serverconnection',
            name='name',
            field=models.CharField(max_length=64, verbose_name='连接名称'),
        ),
        migrations.AddIndex(
            model_name='serverconnection',
            index=models.Index(fields=['tenant', 'project'], name='server_tenant_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='serverconnection',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_server_connection_name'),
        ),
    ]
