# Generated by Django 4.2.3 on 2023-08-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("case_api", "0004_alter_case_project"),
        ("case_ui", "0001_initial"),
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Suite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="套件名称")),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="套件描述"),
                ),
                (
                    "case_api_list",
                    models.ManyToManyField(blank=True, to="case_api.case"),
                ),
                ("case_ui_list", models.ManyToManyField(blank=True, to="case_ui.case")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RunResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="用例路径")),
                ("is_pass", models.BooleanField(default=False, verbose_name="测试通过")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "初始化"),
                            (1, "准备开始"),
                            (2, "正在执行"),
                            (3, "正在正常报告"),
                            (4, "执行完毕"),
                            (-1, "执行出错"),
                        ],
                        default=0,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "create_datetime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "update_datetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="suite.suite"
                    ),
                ),
            ],
        ),
    ]
