# Generated by Django 4.2.3 on 2023-08-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suite", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="cron",
            field=models.CharField(blank=True, max_length=20, verbose_name="cron表达式"),
        ),
        migrations.AddField(
            model_name="suite",
            name="hook_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="hook密钥"),
        ),
        migrations.AddField(
            model_name="suite",
            name="run_type",
            field=models.CharField(
                choices=[("O", "单次执行"), ("C", "Cron"), ("W", "WebHook")],
                default="O",
                max_length=1,
                verbose_name="运行类型",
            ),
        ),
    ]
