# Generated by Django 4.2.3 on 2026-08-03 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0017_task_cluster_alter'),
        ('suite', '0003_suite_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suite',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule'),
        ),
    ]
