# Generated by Django 4.2.3 on 2026-08-04 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_environment_and_more'),
        ('suite', '0004_alter_suite_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.environment', verbose_name='执行环境'),
        ),
    ]
