# Generated by Django 4.2.3 on 2026-08-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_url'),
        ('case_api', '0006_scenario_scenariostep_and_more'),
        ('suite', '0005_suite_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
                ('continue_on_failure', models.BooleanField(default=False, verbose_name='失败后继续下一场景')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_api.scenario')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suite.suite')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SuiteEnvironmentBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, verbose_name='环境别名')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.environment')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_bindings', to='suite.suite')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='suite',
            name='scenarios',
            field=models.ManyToManyField(blank=True, through='suite.SuiteScenario', to='case_api.scenario'),
        ),
        migrations.AddConstraint(
            model_name='suitescenario',
            constraint=models.UniqueConstraint(fields=('suite', 'scenario'), name='unique_suite_scenario'),
        ),
        migrations.AddConstraint(
            model_name='suitescenario',
            constraint=models.UniqueConstraint(fields=('suite', 'order'), name='unique_suite_scenario_order'),
        ),
        migrations.AddConstraint(
            model_name='suiteenvironmentbinding',
            constraint=models.UniqueConstraint(fields=('suite', 'alias'), name='unique_suite_environment_alias'),
        ),
    ]
