# Generated by Django 4.2.3 on 2026-08-05 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0006_suitescenario_suiteenvironmentbinding_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuiteEnvironmentBinding',
        ),
    ]
