# Generated by Django 4.2.3 on 2026-08-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0007_delete_suiteenvironmentbinding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suite',
            name='case_api_list',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='case_ui_list',
        ),
        migrations.RemoveField(
            model_name='suite',
            name='project',
        ),
    ]
