# Generated by Django 4.2.3 on 2026-08-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0008_remove_suite_case_api_list_remove_suite_case_ui_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="runresult",
            name="native_report",
            field=models.JSONField(blank=True, default=dict, verbose_name="原生执行报告"),
        ),
    ]
