# Generated by Django 4.2.3 on 2026-08-08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0009_runresult_native_report"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="suite",
            options={"ordering": ["-id"]},
        ),
    ]
