# Generated by Django 4.2.3 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suite", "0010_alter_suite_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="suite",
            name="execution_timeout",
            field=models.PositiveIntegerField(default=1800, verbose_name="执行超时（秒）"),
        ),
        migrations.AddField(
            model_name="runresult",
            name="cancel_requested",
            field=models.BooleanField(default=False, verbose_name="已请求取消"),
        ),
        migrations.AddField(
            model_name="runresult",
            name="finished_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
        ),
        migrations.AddField(
            model_name="runresult",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AddField(
            model_name="runresult",
            name="timeout_seconds",
            field=models.PositiveIntegerField(default=1800, verbose_name="超时秒数"),
        ),
        migrations.AlterField(
            model_name="runresult",
            name="status",
            field=models.IntegerField(choices=[(0, "初始化"), (1, "准备开始"), (2, "正在执行"), (3, "正在正常报告"), (4, "执行完毕"), (-1, "执行出错"), (-2, "已取消")], default=0, verbose_name="执行状态"),
        ),
    ]
