# Generated by Django 4.2.3 on 2026-08-21 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_ui', '0007_playwrightcase_playwrightstep_and_more'),
        ('suite', '0020_file_retention_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuitePlaywrightCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='suiteexecutionitem',
            name='suite_execution_item_matches_type',
        ),
        migrations.AddField(
            model_name='suiteexecutionitem',
            name='playwright_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_ui.playwrightcase'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event',
            field=models.CharField(choices=[('succeeded', '执行成功'), ('failed', '执行失败'), ('all', '成功或失败')], max_length=16, verbose_name='触发事件'),
        ),
        migrations.AlterField(
            model_name='suiteexecutionitem',
            name='item_type',
            field=models.CharField(choices=[('api', '接口场景'), ('ui', 'UI 用例'), ('playwright_ui', 'Playwright 智能 UI')], max_length=16, verbose_name='类型'),
        ),
        migrations.AddConstraint(
            model_name='suiteexecutionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('playwright_case__isnull', False)), fields=('suite', 'playwright_case'), name='unique_suite_execution_playwright_case'),
        ),
        migrations.AddConstraint(
            model_name='suiteexecutionitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('item_type', 'api'), ('playwright_case__isnull', True), ('scenario__isnull', False), ('ui_case__isnull', True)), models.Q(('item_type', 'ui'), ('playwright_case__isnull', True), ('scenario__isnull', True), ('ui_case__isnull', False)), models.Q(('item_type', 'playwright_ui'), ('playwright_case__isnull', False), ('scenario__isnull', True), ('ui_case__isnull', True)), _connector='OR'), name='suite_execution_item_matches_type'),
        ),
        migrations.AddField(
            model_name='suiteplaywrightcase',
            name='playwright_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_ui.playwrightcase'),
        ),
        migrations.AddField(
            model_name='suiteplaywrightcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suite.suite'),
        ),
        migrations.AddField(
            model_name='suite',
            name='playwright_cases',
            field=models.ManyToManyField(blank=True, through='suite.SuitePlaywrightCase', to='case_ui.playwrightcase'),
        ),
        migrations.AddConstraint(
            model_name='suiteplaywrightcase',
            constraint=models.UniqueConstraint(fields=('suite', 'playwright_case'), name='unique_suite_playwright_case'),
        ),
        migrations.AddConstraint(
            model_name='suiteplaywrightcase',
            constraint=models.UniqueConstraint(fields=('suite', 'order'), name='unique_suite_playwright_case_order'),
        ),
    ]
