# Generated by Django 4.2.3 on 2026-08-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0022_runresult_executor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='runresult',
            name='run_process_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='执行进程 PID'),
        ),
        migrations.AlterField(
            model_name='runresult',
            name='status',
            field=models.IntegerField(choices=[(0, '初始化'), (1, '准备开始'), (2, '正在执行'), (3, '正在正常报告'), (4, '执行完毕'), (-1, '执行出错'), (-2, '已取消'), (-3, '已暂停')], default=0, verbose_name='执行状态'),
        ),
    ]
