# Generated by Django 4.2.3 on 2026-08-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0023_runresult_pause_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='定时配置'),
        ),
        migrations.AddField(
            model_name='suite',
            name='schedule_kind',
            field=models.CharField(choices=[('once', '一次性'), ('daily', '每日'), ('weekly', '每周'), ('monthly', '每月'), ('custom', '自定义 Cron')], default='daily', max_length=12, verbose_name='定时类型'),
        ),
        migrations.AddField(
            model_name='suite',
            name='schedule_timezone',
            field=models.CharField(default='Asia/Shanghai', max_length=64, verbose_name='定时时区'),
        ),
    ]
