# Generated by Django 4.2.3 on 2026-09-07 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_app', '0005_alter_appelement_locator_type'),
        ('suite', '0026_encrypt_webhook_secrets'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteAppCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='suiteexecutionitem',
            name='suite_execution_item_matches_type',
        ),
        migrations.AddField(
            model_name='suiteexecutionitem',
            name='app_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_app.appcase'),
        ),
        migrations.AlterField(
            model_name='suiteexecutionitem',
            name='item_type',
            field=models.CharField(choices=[('api', '接口场景'), ('ui', 'UI 用例'), ('playwright_ui', 'Playwright 智能 UI'), ('app', 'App 用例')], max_length=16, verbose_name='类型'),
        ),
        migrations.AddConstraint(
            model_name='suiteexecutionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('app_case__isnull', False)), fields=('suite', 'app_case'), name='unique_suite_execution_app_case'),
        ),
        migrations.AddConstraint(
            model_name='suiteexecutionitem',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('app_case__isnull', True), ('item_type', 'api'), ('playwright_case__isnull', True), ('scenario__isnull', False), ('ui_case__isnull', True)), models.Q(('app_case__isnull', True), ('item_type', 'ui'), ('playwright_case__isnull', True), ('scenario__isnull', True), ('ui_case__isnull', False)), models.Q(('app_case__isnull', True), ('item_type', 'playwright_ui'), ('playwright_case__isnull', False), ('scenario__isnull', True), ('ui_case__isnull', True)), models.Q(('app_case__isnull', False), ('item_type', 'app'), ('playwright_case__isnull', True), ('scenario__isnull', True), ('ui_case__isnull', True)), _connector='OR'), name='suite_execution_item_matches_type'),
        ),
        migrations.AddField(
            model_name='suiteappcase',
            name='app_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_app.appcase'),
        ),
        migrations.AddField(
            model_name='suiteappcase',
            name='suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suite.suite'),
        ),
        migrations.AddField(
            model_name='suite',
            name='app_cases',
            field=models.ManyToManyField(blank=True, through='suite.SuiteAppCase', to='case_app.appcase'),
        ),
        migrations.AddConstraint(
            model_name='suiteappcase',
            constraint=models.UniqueConstraint(fields=('suite', 'app_case'), name='unique_suite_app_case'),
        ),
        migrations.AddConstraint(
            model_name='suiteappcase',
            constraint=models.UniqueConstraint(fields=('suite', 'order'), name='unique_suite_app_case_order'),
        ),
    ]
