# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_suite_tenants(apps, schema_editor):
    Suite = apps.get_model('suite', 'Suite')
    RunResult = apps.get_model('suite', 'RunResult')
    for suite in Suite.objects.select_related('environment__project').iterator():
        if suite.environment_id:
            Suite.objects.filter(pk=suite.pk).update(tenant_id=suite.environment.project.tenant_id)
    for result in RunResult.objects.select_related('project').iterator():
        if result.tenant_id != result.project.tenant_id:
            RunResult.objects.filter(pk=result.pk).update(tenant_id=result.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('suite', '0027_suiteappcase_and_more'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runresult',
            options={'ordering': ['-create_datetime', '-id']},
        ),
        migrations.AddField(
            model_name='runresult',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='run_results', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='suite',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='suites', to='account.tenant'),
        ),
        migrations.RunPython(backfill_suite_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='runresult',
            index=models.Index(fields=['tenant', 'status', 'create_datetime'], name='run_result_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='suite',
            index=models.Index(fields=['tenant', 'enabled', 'id'], name='suite_tenant_enabled_idx'),
        ),
    ]
