# Generated by Django 4.2.3 on 2026-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0029_backfill_schedule_tenant_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='suite',
            name='creator_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='创建人'),
        ),
    ]
