# Generated by Django 4.2.3 on 2023-08-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Element",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="元素名称")),
                (
                    "by",
                    models.CharField(
                        choices=[
                            ("CLASS_NAME", "CLASS_NAME"),
                            ("CSS_SELECTOR", "CSS_SELECTOR"),
                            ("ID", "ID"),
                            ("LINK_TEXT", "LINK_TEXT"),
                            ("NAME", "NAME"),
                            ("PARTIAL_LINK_TEXT", "PARTIAL_LINK_TEXT"),
                            ("TAG_NAME", "TAG_NAME"),
                            ("XPATH", "XPATH"),
                        ],
                        default="XPATH",
                        max_length=20,
                        verbose_name="定位方式",
                    ),
                ),
                ("value", models.CharField(max_length=255, verbose_name="定位表达式")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用例名称")),
                (
                    "usefixtures",
                    models.JSONField(blank=True, null=True, verbose_name="fixture列表"),
                ),
                ("steps", models.JSONField(blank=True, null=True, verbose_name="用例步骤")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_ui",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
