# Generated by Django 4.2.3 on 2026-08-05 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_ui', '0001_initial'),
        ('suite', '0008_remove_suite_case_api_list_remove_suite_case_ui_list_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Case',
        ),
    ]
