# Generated by Django 4.2.3 on 2026-08-21 21:42

import case_ui.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_recalculate_token_expiry_from_ttl'),
        ('case_ui', '0006_element_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaywrightCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='用例名称')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='用例描述')),
                ('browser', models.CharField(choices=[('chromium', 'Chromium'), ('firefox', 'Firefox'), ('webkit', 'WebKit')], default='chromium', max_length=16, verbose_name='浏览器')),
                ('run_mode', models.CharField(choices=[('headless', '无头模式'), ('headed', '有界面模式')], default='headless', max_length=16, verbose_name='运行模式')),
                ('environment_name', models.CharField(blank=True, default='', max_length=64, verbose_name='执行环境')),
                ('default_timeout', models.PositiveIntegerField(default=10000, verbose_name='默认超时（毫秒）')),
                ('viewport', models.JSONField(blank=True, default=case_ui.models.default_playwright_viewport, verbose_name='视口')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('create_datetime', models.DateTimeField(auto_now_add=True)),
                ('update_datetime', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playwright_cases', to='project.project')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PlaywrightStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
                ('name', models.CharField(max_length=64, verbose_name='步骤名称')),
                ('action', models.CharField(choices=[('goto', '打开页面'), ('input', '输入文本'), ('click', '点击'), ('clear', '清空输入'), ('select', '选择下拉项'), ('check', '勾选'), ('uncheck', '取消勾选'), ('assert_visible', '断言可见'), ('assert_text', '断言文本'), ('save_text', '提取文本'), ('sleep', '固定等待')], max_length=32, verbose_name='操作方式')),
                ('target', models.CharField(blank=True, default='', max_length=512, verbose_name='页面元素/访问地址')),
                ('value', models.TextField(blank=True, default='', verbose_name='操作值')),
                ('locator_mode', models.CharField(choices=[('auto', '智能定位'), ('manual', '手动兜底')], default='auto', max_length=16, verbose_name='定位方式')),
                ('fallback_type', models.CharField(blank=True, default='', max_length=32, verbose_name='备用定位类型')),
                ('fallback_value', models.CharField(blank=True, default='', max_length=512, verbose_name='备用定位表达式')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='扩展配置')),
                ('continue_on_failure', models.BooleanField(default=False, verbose_name='失败后继续')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='case_ui.playwrightcase')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='playwrightstep',
            constraint=models.UniqueConstraint(fields=('case', 'order'), name='unique_playwright_case_step_order'),
        ),
    ]
