# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_ui_tenants(apps, schema_editor):
    for model_name in ('UiCase', 'PlaywrightCase'):
        Model = apps.get_model('case_ui', model_name)
        for item in Model.objects.select_related('project').iterator():
            if item.tenant_id != item.project.tenant_id:
                Model.objects.filter(pk=item.pk).update(tenant_id=item.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('case_ui', '0016_uicase_environment_name'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='playwrightcase',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='playwright_cases', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='uicase',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='ui_cases', to='account.tenant'),
        ),
        migrations.RunPython(backfill_ui_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='playwrightcase',
            index=models.Index(fields=['tenant', 'project', 'id'], name='pw_case_tenant_project_idx'),
        ),
        migrations.AddIndex(
            model_name='uicase',
            index=models.Index(fields=['tenant', 'project', 'id'], name='ui_case_tenant_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='uicase',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'name'), name='unique_tenant_ui_case_name'),
        ),
    ]
