let recording = false; let entries = []; const $ = (id) => document.getElementById(id);
const key = 'autotest-recorder-settings';
function requestToRecord(request) { request.getContent((body) => { if (!recording) return; const data = request.request || {}; const response = request.response || {}; entries.push({ _id: `${Date.now()}-${entries.length}`, request: { method: data.method, url: data.url, headers: data.headers || [], postData: data.postData || {} }, response: { status: response.status, content: { text: body || '' } }, time: request.time || 0 }); render(); }); }
chrome.devtools.network.onRequestFinished.addListener(requestToRecord);
function render(){ $('count').textContent=`${entries.length} 条`; const rows=$('rows'); if(!entries.length){rows.innerHTML='<tr><td colspan="5" class="empty">点击“开始录制”后操作业务页面。</td></tr>';return;} rows.innerHTML=entries.map((entry,i)=>{const r=entry.request,s=entry.response;return `<tr><td><input type="checkbox" data-index="${i}" checked></td><td class="method ${r.method}">${r.method}</td><td class="url" title="${r.url}">${r.url}</td><td>${s.status||'-'}</td><td>${Math.round(entry.time||0)} ms</td></tr>`}).join('');}
function selected(){const checked=[...document.querySelectorAll('input[data-index]:checked')].map(item=>Number(item.dataset.index));return checked.map(index=>entries[index]);}
function download(name, content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'application/json'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
$('start').onclick=()=>{recording=true;$('start').disabled=true;$('stop').disabled=false}; $('stop').onclick=()=>{recording=false;$('start').disabled=false;$('stop').disabled=true}; $('clear').onclick=()=>{entries=[];render()};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(JSON.stringify({records:selected()},null,2));alert('已复制，可粘贴到平台“接口录制”页面。')}catch{alert('复制失败，请使用下载 HAR。')}}; $('download').onclick=()=>download('api-recording.har',JSON.stringify({log:{version:'1.2',creator:{name:'Automation Test Platform Recorder',version:'1.0'},entries:selected()}},null,2));
async function loadSettings(){const value=(await chrome.storage.local.get(key))[key]||{};['platform','token','project','module','conflict'].forEach(id=>$(id).value=value[id]||$(''+id).value)} loadSettings();
$('push').onclick=async()=>{const settings=Object.fromEntries(['platform','token','project','module','conflict'].map(id=>[id,$(id).value]));await chrome.storage.local.set({[key]:settings});if(!settings.platform||!settings.project||!settings.module)return alert('请填写平台地址、项目 ID 和模块 ID。');try{const headers={'Content-Type':'application/json'};if(settings.token)headers.Authorization=`Token ${settings.token}`;const base=settings.platform.replace(/\/$/,'')+'/api/case_api/recording/';const parsed=await fetch(base+'parse/',{method:'POST',headers,body:JSON.stringify({records:selected()})});const parsedJson=await parsed.json();if(!parsed.ok)throw Error(parsedJson.detail||'解析失败');const response=await fetch(base+'import_records/',{method:'POST',headers,body:JSON.stringify({project:Number(settings.project),module:Number(settings.module),conflict_mode:settings.conflict,records:parsedJson.result?.records||parsedJson.records||[]})});const data=await response.json();if(!response.ok)throw Error(data.detail||'保存失败');alert('已推送至平台。')}catch(error){alert(`推送失败：${error.message}`)}};
render();
