# Generated by Django 4.2.3 on 2026-09-04 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import performance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_api', '0031_snapshot_endpoint_rules_to_scenario_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suite', '0026_encrypt_webhook_secrets'),
        ('project', '0021_environment_browser_token_fields'),
        ('monitor', '0010_alter_servicemonitor_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=96, verbose_name='场景名称')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='描述')),
                ('load_type', models.CharField(choices=[('smoke', '冒烟测试'), ('load', '负载测试'), ('stress', '压力测试'), ('spike', '峰值测试'), ('soak', '稳定性测试'), ('custom', '自定义')], default='load', max_length=16, verbose_name='测试类型')),
                ('stages', models.JSONField(default=list, verbose_name='负载阶段')),
                ('thresholds', models.JSONField(blank=True, default=dict, verbose_name='性能阈值')),
                ('scenario_snapshot', models.JSONField(blank=True, default=dict, verbose_name='接口场景快照')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_scenarios', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_scenarios', to='project.environment')),
                ('monitor_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scenarios', to='monitor.monitortarget')),
                ('notification_channels', models.ManyToManyField(blank=True, related_name='performance_scenarios', to='suite.notificationchannel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_scenarios', to='project.project')),
                ('source_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scenarios', to='case_api.scenario')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_no', models.BigIntegerField(db_index=True, default=performance.models.generate_execution_no, unique=True)),
                ('status', models.CharField(choices=[('queued', '等待执行'), ('preparing', '准备环境'), ('running', '执行中'), ('reporting', '汇总报告'), ('passed', '通过'), ('failed', '未通过'), ('error', '执行异常'), ('stopped', '已停止')], db_index=True, default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('current_vus', models.FloatField(default=0)),
                ('current_rps', models.FloatField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('threshold_results', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('work_dir', models.CharField(blank=True, default='', max_length=512)),
                ('process_id', models.PositiveIntegerField(blank=True, null=True)),
                ('stop_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_performance_runs', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_runs', to='project.environment')),
                ('monitor_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_runs', to='monitor.monitortarget')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_runs', to='project.project')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='performance.performancescenario')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetricBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('vus', models.FloatField(default=0)),
                ('rps', models.FloatField(default=0)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('duration_avg', models.FloatField(default=0)),
                ('duration_min', models.FloatField(default=0)),
                ('duration_max', models.FloatField(default=0)),
                ('duration_p90', models.FloatField(default=0)),
                ('duration_p95', models.FloatField(default=0)),
                ('duration_p99', models.FloatField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_buckets', to='performance.performancerun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceEndpointMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_name', models.CharField(max_length=128)),
                ('method', models.CharField(blank=True, default='', max_length=8)),
                ('url', models.CharField(blank=True, default='', max_length=512)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('error_rate', models.FloatField(default=0)),
                ('duration_avg', models.FloatField(default=0)),
                ('duration_p95', models.FloatField(default=0)),
                ('duration_p99', models.FloatField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint_metrics', to='performance.performancerun')),
            ],
            options={
                'ordering': ['-duration_p95', 'endpoint_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='performancescenario',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique_project_performance_scenario'),
        ),
        migrations.AddConstraint(
            model_name='performancemetricbucket',
            constraint=models.UniqueConstraint(fields=('run', 'timestamp'), name='unique_performance_run_bucket'),
        ),
        migrations.AddConstraint(
            model_name='performanceendpointmetric',
            constraint=models.UniqueConstraint(fields=('run', 'endpoint_name'), name='unique_performance_run_endpoint'),
        ),
    ]
