# Generated by Django 4.2.3 on 2026-09-04 10:57

import Tesla.model_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suite', '0026_encrypt_webhook_secrets'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancescenario',
            name='scenario_snapshot',
            field=Tesla.model_fields.EncryptedJSONField(blank=True, default=dict, verbose_name='接口场景快照'),
        ),
        migrations.CreateModel(
            name='PerformanceNotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('failed', '发送失败')], default='failed', max_length=16)),
                ('response_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_summary', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performance_deliveries', to='suite.notificationchannel')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_deliveries', to='performance.performancerun')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
