# Generated by Django 4.2.3 on 2026-09-04 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0031_snapshot_endpoint_rules_to_scenario_steps'),
        ('performance', '0002_alter_performancescenario_scenario_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescenario',
            name='source_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performance_scenarios', to='case_api.endpoint'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='source_type',
            field=models.CharField(choices=[('endpoint', '单接口'), ('scenario', '接口场景')], default='scenario', max_length=16, verbose_name='压测对象'),
        ),
    ]
