# Generated by Django 4.2.3 on 2026-09-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performancescenario_source_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancemetricbucket',
            name='tps',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='performancerun',
            name='current_tps',
            field=models.FloatField(default=0),
        ),
    ]
