# Generated by Django 4.2.3 on 2026-09-04 13:54

import Tesla.model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0004_performancemetricbucket_tps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancescenario',
            name='business_mix',
            field=Tesla.model_fields.EncryptedJSONField(blank=True, default=list, verbose_name='混合业务配置'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='parameter_data',
            field=Tesla.model_fields.EncryptedJSONField(blank=True, default=list, verbose_name='参数化数据'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='parameter_filename',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='参数文件名'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='parameter_format',
            field=models.CharField(blank=True, default='', max_length=8, verbose_name='参数文件格式'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='parameter_strategy',
            field=models.CharField(choices=[('sequential', '顺序循环'), ('random', '随机取值'), ('unique', '全局唯一')], default='sequential', max_length=16, verbose_name='参数取值策略'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='source_mode',
            field=models.CharField(choices=[('single', '单一业务'), ('mixed', '多业务混合')], default='single', max_length=16, verbose_name='业务模式'),
        ),
    ]
