# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_performance_tenants(apps, schema_editor):
    for model_name in ('PerformanceScenario', 'PerformanceRun'):
        Model = apps.get_model('performance', model_name)
        for item in Model.objects.select_related('project').iterator():
            if item.tenant_id != item.project.tenant_id:
                Model.objects.filter(pk=item.pk).update(tenant_id=item.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('performance', '0012_alter_performancemetricbucket_target_vus'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='performancescenario',
            name='unique_project_performance_scenario',
        ),
        migrations.AddField(
            model_name='performancerun',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='performance_runs', to='account.tenant'),
        ),
        migrations.AddField(
            model_name='performancescenario',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='performance_scenarios', to='account.tenant'),
        ),
        migrations.RunPython(backfill_performance_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='performancerun',
            index=models.Index(fields=['tenant', 'status', 'created_at'], name='perf_run_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='performancescenario',
            index=models.Index(fields=['tenant', 'project', 'updated_at'], name='perf_scn_tenant_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='performancescenario',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'name'), name='unique_tenant_performance_scenario'),
        ),
    ]
