# Generated by Django 4.2.3 on 2023-08-17 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="接口名称")),
                ("method", models.CharField(max_length=8, verbose_name="")),
                ("url", models.CharField(max_length=255, verbose_name="")),
                (
                    "params",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="查询字符串"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="表单参数"
                    ),
                ),
                ("json", models.JSONField(max_length=10240, verbose_name="JSON参数")),
                (
                    "cookies",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="Cookies"
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, max_length=10240, null=True, verbose_name="请求头"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Case",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="用例名称")),
                (
                    "allure",
                    models.JSONField(blank=True, null=True, verbose_name="Allure标注"),
                ),
                (
                    "api_args",
                    models.JSONField(blank=True, null=True, verbose_name="接口用例参数"),
                ),
                (
                    "extract",
                    models.JSONField(blank=True, null=True, verbose_name="数据提取"),
                ),
                (
                    "validate",
                    models.JSONField(blank=True, null=True, verbose_name="断言"),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_api.endpoint",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
