# Generated by Django 4.2.3 on 2023-08-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="json",
            field=models.JSONField(
                blank=True, max_length=10240, null=True, verbose_name="JSON参数"
            ),
        ),
    ]
