# Generated by Django 4.2.3 on 2023-08-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_api", "0002_alter_endpoint_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="validate",
            field=models.JSONField(verbose_name="断言"),
        ),
    ]
