# Generated by Django 4.2.3 on 2023-08-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_remove_project_user_project_pm_project_user_list"),
        ("case_api", "0003_alter_case_validate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="case",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_api",
                to="project.project",
            ),
        ),
    ]
