# Generated by Django 4.2.3 on 2026-08-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0004_alter_case_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='method',
            field=models.CharField(max_length=8, verbose_name='请求方法'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='url',
            field=models.CharField(max_length=255, verbose_name='接口地址'),
        ),
    ]
