# Generated by Django 4.2.3 on 2026-08-05 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_url'),
        ('case_api', '0005_alter_endpoint_method_alter_endpoint_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='场景名称')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='场景描述')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='project.project')),
            ],
            options={
                'ordering': ['project_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='步骤名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
                ('environment_alias', models.CharField(default='default', max_length=64, verbose_name='环境别名')),
                ('request_override', models.JSONField(blank=True, default=dict, verbose_name='参数覆盖')),
                ('extract', models.JSONField(blank=True, default=dict, verbose_name='数据提取')),
                ('validate', models.JSONField(blank=True, default=dict, verbose_name='断言')),
                ('continue_on_failure', models.BooleanField(default=False, verbose_name='失败后继续')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_api.case')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='case_api.scenario')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scenariostep',
            constraint=models.UniqueConstraint(fields=('scenario', 'order'), name='unique_scenario_step_order'),
        ),
    ]
