# Generated by Django 4.2.3 on 2026-08-05 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_url'),
        ('case_api', '0006_scenario_scenariostep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostep',
            name='environment_alias',
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='project.environment'),
        ),
    ]
