# Generated by Django 4.2.3 on 2026-08-05 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0007_remove_scenariostep_environment_alias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostep',
            name='environment',
        ),
    ]
