# Generated by Django 4.2.3 on 2026-08-05 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0008_remove_scenariostep_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scenariostep',
            name='case',
        ),
        migrations.AddField(
            model_name='scenariostep',
            name='endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='case_api.endpoint'),
        ),
    ]
