# Generated by Django 4.2.3 on 2026-08-05 04:22

from django.db import migrations, models


def copy_primary_project_to_projects(apps, schema_editor):
    Scenario = apps.get_model('case_api', 'Scenario')
    for scenario in Scenario.objects.all().iterator():
        scenario.projects.add(scenario.project_id)


def clear_projects(apps, schema_editor):
    Scenario = apps.get_model('case_api', 'Scenario')
    for scenario in Scenario.objects.all().iterator():
        scenario.projects.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_project_url'),
        ('case_api', '0010_delete_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='linked_scenarios', to='project.project'),
        ),
        migrations.RunPython(copy_primary_project_to_projects, clear_projects),
    ]
