# Generated by Django 4.2.3 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0011_scenario_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="files",
            field=models.JSONField(blank=True, default=dict, verbose_name="上传文件"),
        ),
    ]
