# Generated by Django 4.2.3 on 2026-08-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0012_endpoint_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariostep",
            name="polling",
            field=models.JSONField(blank=True, default=dict, verbose_name="轮询等待"),
        ),
    ]
