# Generated by Django 4.2.3 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0014_endpointmodule_endpoint_module"),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="parametrize",
            field=models.JSONField(blank=True, default=list, verbose_name="数据驱动参数"),
        ),
    ]
