# Generated by Django 4.2.3 on 2026-08-18 17:58

from django.db import migrations, models
import django.db.models.deletion


def create_main_flow_nodes(apps, schema_editor):
    ScenarioStep = apps.get_model("case_api", "ScenarioStep")
    ScenarioFlowNode = apps.get_model("case_api", "ScenarioFlowNode")
    for step in ScenarioStep.objects.all().order_by("scenario_id", "order", "id").iterator():
        ScenarioFlowNode.objects.get_or_create(
            step_id=step.id,
            defaults={
                "scenario_id": step.scenario_id,
                "node_type": "endpoint",
                "name": step.name,
                "order": step.order,
            },
        )


def remove_main_flow_nodes(apps, schema_editor):
    ScenarioFlowNode = apps.get_model("case_api", "ScenarioFlowNode")
    ScenarioFlowNode.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0019_normalize_variable_placeholders'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='分支名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='优先级')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认分支')),
                ('conditions', models.JSONField(blank=True, default=list, verbose_name='条件明细')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioFlowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('endpoint', '接口步骤'), ('condition', '判断分支')], max_length=16, verbose_name='节点类型')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='节点名称')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='执行顺序')),
                ('condition_logic', models.CharField(default='and', max_length=8, verbose_name='条件关系')),
                ('parent_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='case_api.scenariobranch')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_nodes', to='case_api.scenario')),
                ('step', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flow_node', to='case_api.scenariostep')),
            ],
            options={
                'ordering': ['parent_branch_id', 'order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='scenariobranch',
            name='condition_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='case_api.scenarioflownode', verbose_name='判断节点'),
        ),
        migrations.AddConstraint(
            model_name='scenariobranch',
            constraint=models.UniqueConstraint(fields=('condition_node', 'order'), name='unique_scenario_branch_order'),
        ),
        migrations.RunPython(create_main_flow_nodes, remove_main_flow_nodes),
    ]
