# Generated by Django 4.2.3 on 2026-08-18 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0020_scenario_flow_nodes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scenariostep',
            name='unique_scenario_step_order',
        ),
    ]
