# Generated by Django 4.2.3 on 2026-08-18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0021_scenario_step_order_legacy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scenariobranch",
            name="is_default",
        ),
    ]
