# Generated by Django 4.2.3 on 2026-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0022_remove_scenario_branch_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenariostep",
            name="request_method",
            field=models.CharField(blank=True, max_length=8, verbose_name="请求方式覆盖"),
        ),
        migrations.AddField(
            model_name="scenariostep",
            name="request_url",
            field=models.CharField(blank=True, max_length=255, verbose_name="请求地址覆盖"),
        ),
    ]
