# Generated by Codex on 2026-08-27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0026_scenariostep_failure_retry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scenariostep",
            name="endpoint",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="case_api.endpoint"),
        ),
    ]
