# Generated by Codex on 2026-08-27

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ("case_api", "0027_scenariostep_endpoint_set_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=timezone.now, verbose_name="创建时间"),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name="scenario",
            options={"ordering": ["-created_at", "-id"]},
        ),
    ]
