# Generated by Django 4.2.3 on 2026-09-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_api', '0033_endpoint_body_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenarioflownode',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='启用节点'),
        ),
    ]
