# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_scenario_tenant(apps, schema_editor):
    Scenario = apps.get_model('case_api', 'Scenario')
    for scenario in Scenario.objects.select_related('project').iterator():
        if scenario.tenant_id != scenario.project.tenant_id:
            Scenario.objects.filter(pk=scenario.pk).update(tenant_id=scenario.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('case_api', '0034_scenarioflownode_enabled'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='api_scenarios', to='account.tenant'),
        ),
        migrations.RunPython(backfill_scenario_tenant, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['tenant', 'project', 'created_at'], name='api_scn_tenant_proj_idx'),
        ),
        migrations.AddConstraint(
            model_name='scenario',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'name'), name='unique_tenant_api_scenario_name'),
        ),
    ]
