# Generated by Django 4.2.3 on 2026-08-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0009_encrypt_prometheus_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicemonitor",
            name="address",
            field=models.CharField(
                help_text="HTTP 使用完整 URL；TCP 使用主机名或 IP；Docker 使用容器名称",
                max_length=512,
                verbose_name="服务地址",
            ),
        ),
        migrations.AlterField(
            model_name="servicemonitor",
            name="monitor_type",
            field=models.CharField(
                choices=[("http", "HTTP"), ("tcp", "TCP"), ("docker", "Docker 容器")],
                default="http",
                max_length=16,
                verbose_name="监控类型",
            ),
        ),
    ]
