# Generated by Django 4.2.3 on 2026-09-14 11:10

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_monitor_tenants(apps, schema_editor):
    PrometheusInstance = apps.get_model('monitor', 'PrometheusInstance')
    MonitorCluster = apps.get_model('monitor', 'MonitorCluster')
    MonitorTarget = apps.get_model('monitor', 'MonitorTarget')
    ServiceMonitor = apps.get_model('monitor', 'ServiceMonitor')

    for instance in PrometheusInstance.objects.select_related('project').iterator():
        if instance.project_id:
            PrometheusInstance.objects.filter(pk=instance.pk).update(
                tenant_id=instance.project.tenant_id,
            )
    for cluster in MonitorCluster.objects.select_related('project').iterator():
        MonitorCluster.objects.filter(pk=cluster.pk).update(
            tenant_id=cluster.project.tenant_id,
        )
    for target in MonitorTarget.objects.select_related('project', 'prometheus').iterator():
        tenant_id = target.project.tenant_id if target.project_id else target.prometheus.tenant_id
        MonitorTarget.objects.filter(pk=target.pk).update(tenant_id=tenant_id)
    for service in ServiceMonitor.objects.select_related('project').iterator():
        if service.project_id:
            ServiceMonitor.objects.filter(pk=service.pk).update(
                tenant_id=service.project.tenant_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_tenant_max_performance_worker_count'),
        ('monitor', '0010_alter_servicemonitor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitorcluster',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='monitor_clusters', to='account.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='monitortarget',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='monitor_targets', to='account.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='prometheusinstance',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='prometheus_instances', to='account.tenant', verbose_name='所属租户'),
        ),
        migrations.AddField(
            model_name='servicemonitor',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='service_monitors', to='account.tenant', verbose_name='所属租户'),
        ),
        migrations.RunPython(backfill_monitor_tenants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='prometheusinstance',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
        migrations.AddIndex(
            model_name='monitorcluster',
            index=models.Index(fields=['tenant', 'project'], name='cluster_tenant_project_idx'),
        ),
        migrations.AddIndex(
            model_name='monitortarget',
            index=models.Index(fields=['tenant', 'project'], name='target_tenant_project_idx'),
        ),
        migrations.AddIndex(
            model_name='prometheusinstance',
            index=models.Index(fields=['tenant', 'project'], name='prom_tenant_project_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemonitor',
            index=models.Index(fields=['tenant', 'project'], name='service_tenant_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='prometheusinstance',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_tenant_prometheus_name'),
        ),
    ]
