# Generated by Django 4.2.3 on 2026-09-13 15:08

import account.models
from django.db import migrations, models
import django.db.models.deletion


def backfill_template_tenants(apps, schema_editor):
    Template = apps.get_model('execution_template', 'ExecutionTemplate')
    for template in Template.objects.select_related('project').iterator():
        if template.tenant_id != template.project.tenant_id:
            Template.objects.filter(pk=template.pk).update(tenant_id=template.project.tenant_id)


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_tenant_tenantmembership'),
        ('execution_template', '0003_encrypt_template_parameters'),
        ('project', '0023_project_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='executiontemplate',
            name='tenant',
            field=models.ForeignKey(default=account.models.get_default_tenant_id, editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='execution_templates', to='account.tenant'),
        ),
        migrations.RunPython(backfill_template_tenants, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='executiontemplate',
            index=models.Index(fields=['tenant', 'project', 'id'], name='exec_tpl_tenant_project_idx'),
        ),
        migrations.AddConstraint(
            model_name='executiontemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'project', 'name'), name='unique_tenant_execution_template'),
        ),
    ]
