<template>
  <div class="notification-page">
    <header><div><h2>通知管理</h2><p>配置飞书、企业微信 Webhook，并跟踪每一次执行结果投递。</p></div></header>
    <n-tabs type="line" animated>
      <n-tab-pane name="channels" tab="通知渠道"><n-card title="通知渠道"><template #header-extra><n-button type="primary" @click="openChannel()">新增渠道</n-button></template><n-data-table :columns="channelColumns" :data="channels" :loading="loading" /></n-card></n-tab-pane>
      <n-tab-pane name="rules" tab="通知规则"><n-card title="通知规则"><template #header-extra><n-button type="primary" @click="openRule()">新增规则</n-button></template><n-data-table :columns="ruleColumns" :data="rules" :loading="loading" /></n-card></n-tab-pane>
      <n-tab-pane name="deliveries" tab="投递记录"><n-card title="投递记录"><template #header-extra><n-button @click="load">刷新</n-button></template><n-data-table :columns="deliveryColumns" :data="deliveries" :loading="loading" :pagination="{ pageSize: 10 }" /></n-card></n-tab-pane>
    </n-tabs>
    <n-modal v-model:show="showChannel" preset="card" :title="channel.id ? '编辑渠道' : '新增渠道'" style="width:560px"><n-form label-placement="top"><n-form-item label="名称"><n-input v-model:value="channel.name" /></n-form-item><n-form-item label="关联项目"><n-select v-model:value="channel.projects" multiple :options="projectOptions" placeholder="可选择多个项目" /></n-form-item><n-form-item label="平台"><n-select v-model:value="channel.platform" :options="[{label:'飞书',value:'lark'},{label:'企业微信',value:'wecom'}]" /></n-form-item><n-form-item label="Webhook 地址"><n-input v-model:value="channel.webhook_url" /></n-form-item><n-switch v-model:value="channel.enabled">启用</n-switch><n-button block type="primary" style="margin-top:20px" @click="saveChannel">保存</n-button></n-form></n-modal>
    <n-modal v-model:show="showRule" preset="card" :title="rule.id ? '编辑规则' : '新增规则'" style="width:560px"><n-form label-placement="top"><n-form-item label="通知渠道"><n-select v-model:value="rule.channel" :options="channelOptions" /></n-form-item><n-form-item label="套件（留空表示关联项目下的全部套件）"><n-select v-model:value="rule.suite" clearable :disabled="!rule.channel" :options="availableSuiteOptions" placeholder="请先选择通知渠道" /></n-form-item><n-form-item label="触发事件"><n-select v-model:value="rule.event" :options="eventOptions" /></n-form-item><n-switch v-model:value="rule.enabled">启用</n-switch><n-button block type="primary" style="margin-top:20px" @click="saveRule">保存</n-button></n-form></n-modal>
  </div>
</template>
<script setup lang="ts">
import { computed, h, onMounted, reactive, ref, watch } from 'vue'; import { NButton, NTag, useMessage } from 'naive-ui'; import { ProjectAPI } from '@/api/project/http'; import { SuiteAPI, NotificationChannelAPI, NotificationDeliveryAPI, NotificationRuleAPI } from '@/api/suite/http';
const msg=useMessage(), ca=new NotificationChannelAPI(), ra=new NotificationRuleAPI(), da=new NotificationDeliveryAPI(), pa=new ProjectAPI(), sa=new SuiteAPI(); const loading=ref(false),channels=ref<any[]>([]),rules=ref<any[]>([]),deliveries=ref<any[]>([]),projectOptions=ref<any[]>([]),suiteOptions=ref<any[]>([]),showChannel=ref(false),showRule=ref(false); const channel=reactive<any>({name:'',projects:[],platform:'lark',webhook_url:'',enabled:true}),rule=reactive<any>({channel:null,suite:null,event:'failed',enabled:true}); const channelOptions=ref<any[]>([]); const eventOptions=[{label:'执行成功',value:'succeeded'},{label:'执行失败',value:'failed'},{label:'成功/失败',value:'all'}]; const eventLabel=(e:any)=>e==='succeeded'?'执行成功':e==='failed'?'执行失败':e==='all'?'成功或失败':'-';
const availableSuiteOptions=computed(()=>{const selected=channels.value.find((item:any)=>item.id===rule.channel);const projectIds=selected?.projects||[];return suiteOptions.value.filter((item:any)=>projectIds.includes(item.project)).map((item:any)=>({label:item.name,value:item.id}))}); watch(()=>rule.channel,()=>{if(rule.suite&&!availableSuiteOptions.value.some((item:any)=>item.value===rule.suite))rule.suite=null});
const action=(label:string,fn:any,type:any='primary')=>h(NButton,{text:true,type,onClick:fn},{default:()=> label}); const channelColumns=[{title:'名称',key:'name'},{title:'关联项目',key:'project_names',render:(r:any)=>(r.project_names||[]).join('、')||'-'},{title:'平台',key:'platform',render:(r:any)=>h(NTag,{type:'info'},()=>r.platform==='lark'?'飞书':'企业微信')},{title:'Webhook',key:'webhook_url',ellipsis:true},{title:'状态',key:'enabled',render:(r:any)=>h(NTag,{type:r.enabled?'success':'default'},()=>r.enabled?'启用':'停用')},{title:'操作',key:'actions',width:210,render:(r:any)=>h('div',{class:'table-actions'},[action('测试发送',()=>testChannel(r)),action('编辑',()=>openChannel(r)),action('删除',()=>removeChannel(r),'error')])}]; const ruleColumns=[{title:'渠道',key:'channel_name'},{title:'套件',key:'suite_name',render:(r:any)=>r.suite_name||'全部套件'},{title:'事件',key:'event',render:(r:any)=>eventLabel(r.event)},{title:'状态',key:'enabled',render:(r:any)=>h(NTag,{type:r.enabled?'success':'default'},()=>r.enabled?'启用':'停用')},{title:'操作',key:'actions',width:140,render:(r:any)=>h('div',{class:'table-actions'},[action('编辑',()=>openRule(r)),action('删除',()=>removeRule(r),'error')])}]; const deliveryColumns=[{title:'执行编号',key:'result'},{title:'渠道',key:'channel',render:(r:any)=>h('span',{class:'delivery-channel-cell'},[h('span',{class:'ch-name'}, r.channel_name || '-'),h(NTag,{size:'small',type:'info',bordered:false,style:{marginLeft:'6px'}},()=>r.channel_platform==='lark'?'飞书':(r.channel_platform==='wecom'?'企业微信':'-'))])},{title:'事件',key:'event',render:(r:any)=>eventLabel(r.event)},{title:'状态',key:'status'},{title:'HTTP',key:'response_code'},{title:'响应摘要',key:'response_summary',ellipsis:true},{title:'时间',key:'created_at'}];
function reset(o:any,v:any){Object.keys(o).forEach(k=>delete o[k]);Object.assign(o,v)} function openChannel(v?:any){reset(channel,v?{...v,projects:[...(v.projects||[])]}:{name:'',projects:[],platform:'lark',webhook_url:'',enabled:true});showChannel.value=true} function openRule(v?:any){reset(rule,v||{channel:null,suite:null,event:'failed',enabled:true});showRule.value=true} async function load(){loading.value=true;try{[channels.value,rules.value,deliveries.value]=await Promise.all([ca.getDataList({}),ra.getDataList({}),da.getDataList({})]);channelOptions.value=channels.value.map((x:any)=>({label:x.name,value:x.id}))}finally{loading.value=false}} async function saveChannel(){try{channel.id?await ca.update(channel.id,channel):await ca.createData(channel);showChannel.value=false;msg.success('已保存');load()}catch(e:any){msg.error(e.message||'保存失败')}} async function saveRule(){try{rule.id?await ra.update(rule.id,rule):await ra.createData(rule);showRule.value=false;msg.success('已保存');load()}catch(e:any){msg.error(e.message||'保存失败')}} onMounted(async()=>{projectOptions.value=(await pa.getDataList({})).map((x:any)=>({label:x.name,value:x.id}));suiteOptions.value=(await sa.getDataList({}));load()})
async function testChannel(v:any){try{await ca.test(v.id);msg.success('测试消息已发送')}catch(e:any){msg.error(e.message||'发送失败')}} async function removeChannel(v:any){await ca.DeleteDataByID(v.id);msg.success('已删除');load()} async function removeRule(v:any){await ra.DeleteDataByID(v.id);msg.success('已删除');load()}
</script><style scoped>.notification-page{max-width:1200px;margin:20px auto}.notification-page header{margin-bottom:18px}.notification-page h2{margin:0;color:#172033}.notification-page p{margin:6px 0;color:#7d899b}.notification-page :deep(.n-card){border-radius:12px}.notification-page :deep(.table-actions){display:flex;align-items:center;gap:12px;white-space:nowrap}.notification-page :deep(.table-actions .n-button){margin:0;padding:0 2px}</style>
