<template>
  <n-result v-if="projectsLoaded && !canMaintain" class="access-denied" status="403" title="无访问权限" description="仅系统管理员或项目负责人可以维护监控配置。" />
  <section v-else class="monitor-config">
    <header class="monitor-header"><div><h2>监控配置</h2><p>维护 Prometheus 地址、node_exporter 目标和基础告警阈值。</p></div><div class="header-actions"><n-select v-model:value="selectedProject" clearable class="project-filter" :options="baseProjectOptions" placeholder="全部项目" @update:value="load" /><n-button v-if="isAdmin" type="primary" ghost @click="router.push({ name: 'monitor_check_settings' })">监控频率设置</n-button></div></header>
    <n-tabs v-model:value="activeTab" type="line">
      <n-tab-pane name="prometheus" tab="Prometheus 实例"><div class="toolbar"><n-button type="primary" @click="openPrometheus()">新增 Prometheus</n-button></div><n-data-table striped :columns="prometheusColumns" :data="prometheus" :loading="loading" /></n-tab-pane>
      <n-tab-pane name="clusters" tab="集群管理"><div class="toolbar"><n-button type="primary" @click="openCluster()">新增集群</n-button></div><n-data-table striped :columns="clusterColumns" :data="clusters" :loading="loading" /></n-tab-pane>
      <n-tab-pane name="targets" tab="监控目标"><div class="toolbar"><n-button type="primary" @click="openTarget()">新增监控目标</n-button></div><n-data-table striped :columns="targetColumns" :data="targets" :loading="loading" /></n-tab-pane>
      <n-tab-pane name="services" tab="服务监控"><div class="toolbar"><n-button type="primary" @click="openService()">新增服务监控</n-button></div><n-data-table striped :columns="serviceColumns" :data="services" :loading="loading" /></n-tab-pane>
    </n-tabs>
    <n-modal v-model:show="prometheusVisible" preset="card" :title="editingPrometheus?.id ? '编辑 Prometheus' : '新增 Prometheus'" class="platform-form-modal">
      <n-form :model="prometheusForm" label-placement="top"><n-form-item label="所属项目"><n-select v-model:value="prometheusForm.project" :options="formProjectOptions" placeholder="请选择所属项目" /></n-form-item><n-form-item label="名称"><n-input v-model:value="prometheusForm.name" placeholder="例如：生产 Prometheus" /></n-form-item><n-form-item label="Prometheus 地址"><n-input v-model:value="prometheusForm.base_url" placeholder="http://172.18.0.1:9090" /></n-form-item><n-form-item :label="editingPrometheus?.access_token_configured ? '访问令牌（留空保持原值）' : '访问令牌（可选）'"><n-input v-model:value="prometheusForm.access_token" type="password" :input-props="{ autocomplete: 'new-password' }" /></n-form-item><n-form-item label="备注"><n-input v-model:value="prometheusForm.description" /></n-form-item><n-switch v-model:value="prometheusForm.enabled" /> 启用实例</n-form>
      <template #footer><n-space justify="end"><n-button @click="prometheusVisible = false">取消</n-button><n-button type="primary" @click="savePrometheus">保存</n-button></n-space></template>
    </n-modal>
    <n-modal v-model:show="serviceVisible" preset="card" :title="editingService?.id ? '编辑服务监控' : '新增服务监控'" class="platform-form-modal">
      <n-form :model="serviceForm" label-placement="top"><n-grid :cols="2" :x-gap="16"><n-gi><n-form-item label="服务名称"><n-input v-model:value="serviceForm.name" placeholder="例如：平台后端" /></n-form-item></n-gi><n-gi><n-form-item label="监控类型"><n-select v-model:value="serviceForm.monitor_type" :options="[{ label: 'HTTP', value: 'http' }, { label: 'TCP', value: 'tcp' }, { label: 'Docker 容器', value: 'docker' }]" /></n-form-item></n-gi><n-gi><n-form-item label="所属项目"><n-select v-model:value="serviceForm.project" :options="formProjectOptions" @update:value="onServiceProjectChange" /></n-form-item></n-gi><n-gi><n-form-item label="关联服务器"><n-select v-model:value="serviceForm.server" clearable :options="serviceServerOptions" /></n-form-item></n-gi><n-gi><n-form-item :label="serviceForm.monitor_type === 'http' ? '服务 URL' : serviceForm.monitor_type === 'tcp' ? '主机地址' : '容器名称'"><n-input v-model:value="serviceForm.address" :placeholder="serviceForm.monitor_type === 'http' ? 'http://127.0.0.1:8000/health/' : serviceForm.monitor_type === 'tcp' ? '127.0.0.1' : 'test-platform-backend-1'" /></n-form-item></n-gi><n-gi><n-form-item label="端口"><n-input-number v-model:value="serviceForm.port" :disabled="serviceForm.monitor_type !== 'tcp'" :min="1" :max="65535" placeholder="TCP 必填" /></n-form-item></n-gi><n-gi><n-form-item label="期望 HTTP 状态码"><n-select v-model:value="serviceForm.expected_status_codes" multiple tag :disabled="serviceForm.monitor_type !== 'http'" :options="httpCodeOptions" /></n-form-item></n-gi><n-gi><n-form-item label="超时（秒）"><n-input-number v-model:value="serviceForm.timeout_seconds" :min="1" :max="60" /></n-form-item></n-gi></n-grid><n-switch v-model:value="serviceForm.enabled" /> 启用监控</n-form>
      <template #footer><n-space justify="end"><n-button @click="serviceVisible = false">取消</n-button><n-button :disabled="!editingService?.id" @click="testService">测试服务</n-button><n-button type="primary" @click="saveService">保存</n-button></n-space></template>
    </n-modal>
    <n-modal v-model:show="targetVisible" preset="card" :title="editingTarget?.id ? '编辑监控目标' : '新增监控目标'" class="platform-form-modal">
      <n-alert v-if="!prometheus.length" type="warning" class="target-form-tip">请先在“Prometheus 实例”页签新增并保存一个 Prometheus 实例。</n-alert>
      <n-form :model="targetForm" label-placement="top"><n-grid :cols="2" :x-gap="16"><n-gi><n-form-item label="目标名称"><n-input v-model:value="targetForm.name" placeholder="例如：生产服务器" /></n-form-item></n-gi><n-gi><n-form-item label="所属项目"><n-select v-model:value="targetForm.project" :options="formProjectOptions" @update:value="onTargetProjectChange" /></n-form-item></n-gi><n-gi><n-form-item label="Prometheus 实例"><n-select v-model:value="targetForm.prometheus" :options="prometheusOptions" placeholder="请选择当前项目的 Prometheus 实例" /></n-form-item></n-gi><n-gi><n-form-item label="关联服务器"><n-select v-model:value="targetForm.server" clearable :options="targetServerOptions" /></n-form-item></n-gi><n-gi><n-form-item label="Job"><n-input v-model:value="targetForm.job" placeholder="node" /></n-form-item></n-gi><n-gi><n-form-item label="Instance 标签"><n-input v-model:value="targetForm.instance_label" placeholder="172.17.0.1:9100" /></n-form-item></n-gi></n-grid><div class="threshold-title">告警阈值（预警 / 告警）</div><n-grid :cols="3" :x-gap="16"><n-gi><n-form-item label="CPU (%)"><div class="threshold-inputs"><n-input-number v-model:value="targetForm.cpu_warning_threshold" :min="1" :max="99" /><n-input-number v-model:value="targetForm.cpu_critical_threshold" :min="2" :max="100" /></div></n-form-item></n-gi><n-gi><n-form-item label="内存 (%)"><div class="threshold-inputs"><n-input-number v-model:value="targetForm.memory_warning_threshold" :min="1" :max="99" /><n-input-number v-model:value="targetForm.memory_critical_threshold" :min="2" :max="100" /></div></n-form-item></n-gi><n-gi><n-form-item label="磁盘 (%)"><div class="threshold-inputs"><n-input-number v-model:value="targetForm.disk_warning_threshold" :min="1" :max="99" /><n-input-number v-model:value="targetForm.disk_critical_threshold" :min="2" :max="100" /></div></n-form-item></n-gi></n-grid><n-switch v-model:value="targetForm.enabled" /> 启用监控</n-form>
      <template #footer><n-space justify="end"><n-button @click="targetVisible = false">取消</n-button><n-button :disabled="!editingTarget?.id" @click="testTarget">测试指标</n-button><n-button type="primary" @click="saveTarget">保存</n-button></n-space></template>
    </n-modal>
    <n-modal v-model:show="clusterVisible" preset="card" :title="editingCluster?.id ? '编辑集群' : '新增集群'" class="platform-form-modal"><n-alert type="info" class="target-form-tip">Prometheus 负责服务发现，平台按 Job 和标签规则自动同步节点。</n-alert><n-form :model="clusterForm" label-placement="top"><n-grid :cols="2" :x-gap="16"><n-gi><n-form-item label="集群名称"><n-input v-model:value="clusterForm.name" /></n-form-item></n-gi><n-gi><n-form-item label="所属项目"><n-select v-model:value="clusterForm.project" :options="formProjectOptions" @update:value="onClusterProjectChange" /></n-form-item></n-gi><n-gi><n-form-item label="Prometheus 实例"><n-select v-model:value="clusterForm.prometheus" :options="clusterPrometheusOptions" /></n-form-item></n-gi><n-gi><n-form-item label="查询服务器"><n-select v-model:value="clusterForm.server" clearable :options="clusterServerOptions" /></n-form-item></n-gi><n-gi><n-form-item label="服务发现方式"><n-select v-model:value="clusterForm.discovery_type" :options="discoveryOptions" /></n-form-item></n-gi><n-gi><n-form-item label="Job"><n-input v-model:value="clusterForm.job" /></n-form-item></n-gi><n-gi><n-form-item label="Instance 标签名"><n-input v-model:value="clusterForm.instance_label_key" /></n-form-item></n-gi><n-gi><n-form-item label="节点名称标签"><n-input v-model:value="clusterForm.node_name_label" /></n-form-item></n-gi></n-grid><n-form-item label="标签规则（每行：标签名=匹配值）"><n-input v-model:value="clusterLabelsText" type="textarea" placeholder="cluster=production&#10;environment=prod" /></n-form-item><n-switch v-model:value="clusterForm.enabled" /> 自动同步节点</n-form><template #footer><n-space justify="end"><n-button @click="clusterVisible = false">取消</n-button><n-button :disabled="!editingCluster?.id" @click="syncCluster(editingCluster!)">立即同步</n-button><n-button type="primary" @click="saveCluster">保存</n-button></n-space></template></n-modal>
  </section>
</template>

<script setup lang="ts">
  import { computed, h, onMounted, reactive, ref, watch } from 'vue';
  import { useRouter } from 'vue-router';
  import { NButton, NPopconfirm, NSpace, NTag, useMessage } from 'naive-ui';
  import { MonitorAPI, type MonitorCluster, type MonitorTarget, type PrometheusInstance, type ServiceMonitor } from '@/api/monitor/http';
  import { useUserStore } from '@/store/modules/user';
  import { http } from '@/utils/http/axios';
  import { ServerConnectionAPI } from '@/api/system/server';
  const props = withDefaults(defineProps<{ defaultTab?: string }>(), { defaultTab: 'prometheus' });
  const router = useRouter();
  const activeTab = ref(props.defaultTab);
  watch(() => props.defaultTab, (value) => { activeTab.value = value; });
  const message = useMessage(); const userStore = useUserStore(); const isAdmin = computed(() => Boolean((userStore.info as any)?.is_admin)); const currentUserId = computed(() => Number((userStore.info as any)?.user || (userStore.info as any)?.id || 0)); const loading = ref(false); const projectsLoaded = ref(false); const selectedProject = ref<number | null>(null); const prometheus = ref<PrometheusInstance[]>([]); const targets = ref<MonitorTarget[]>([]); const services = ref<ServiceMonitor[]>([]); const projects = ref<any[]>([]); const servers = ref<any[]>([]); const prometheusVisible = ref(false); const targetVisible = ref(false); const serviceVisible = ref(false); const editingPrometheus = ref<PrometheusInstance>(); const editingTarget = ref<MonitorTarget>(); const editingService = ref<ServiceMonitor>();
  const clusters = ref<MonitorCluster[]>([]); const clusterVisible = ref(false); const editingCluster = ref<MonitorCluster>(); const clusterLabelsText = ref('');
  const emptyPrometheus = (): PrometheusInstance => ({ project: selectedProject.value, name: '', base_url: '', access_token: '', enabled: true, description: '' }); const emptyTarget = (): MonitorTarget => ({ prometheus: null, project: selectedProject.value, server: null, name: '', job: 'node', instance_label: '', extra_labels: {}, enabled: true, cpu_warning_threshold: 80, cpu_critical_threshold: 90, memory_warning_threshold: 85, memory_critical_threshold: 95, disk_warning_threshold: 80, disk_critical_threshold: 90 }); const emptyService = (): ServiceMonitor => ({ project: selectedProject.value, server: null, name: '', monitor_type: 'http', address: '', port: null, expected_status_codes: [200], timeout_seconds: 5, enabled: true }); const prometheusForm = reactive<PrometheusInstance>(emptyPrometheus()); const targetForm = reactive<MonitorTarget>(emptyTarget()); const serviceForm = reactive<ServiceMonitor>(emptyService()); const httpCodeOptions = [200, 201, 202, 204, 301, 302].map((value) => ({ label: String(value), value }));
  const managedProjects = computed(() => isAdmin.value ? projects.value : projects.value.filter((item) => Number(item.pm) === currentUserId.value));
  const canMaintain = computed(() => isAdmin.value || managedProjects.value.length > 0);
  const managedProjectIds = computed(() => new Set(managedProjects.value.map((item) => Number(item.id))));
  const baseProjectOptions = computed(() => managedProjects.value.map((item) => ({ label: item.name, value: Number(item.id) })));
  const emptyCluster = (): MonitorCluster => ({ project: selectedProject.value, prometheus: null, server: null, name: '', discovery_type: 'prometheus', job: 'node', label_rules: {}, instance_label_key: 'instance', node_name_label: 'instance', enabled: true, cpu_warning_threshold: 80, cpu_critical_threshold: 90, memory_warning_threshold: 85, memory_critical_threshold: 95, disk_warning_threshold: 80, disk_critical_threshold: 90 }); const clusterForm = reactive<MonitorCluster>(emptyCluster());
  const discoveryOptions = [{ label: 'Prometheus Targets（通用）', value: 'prometheus' }, { label: 'Kubernetes 服务发现', value: 'kubernetes' }, { label: '文件服务发现', value: 'file_sd' }, { label: '云服务发现', value: 'cloud' }];
  const formProjectOptions = computed(() => selectedProject.value == null ? baseProjectOptions.value : baseProjectOptions.value.filter((item) => item.value === selectedProject.value));
  const prometheusOptions = computed(() => prometheus.value.filter((item) => Number(item.project) === Number(targetForm.project)).map((item) => ({ label: item.name, value: item.id })));
  const targetServerOptions = computed(() => servers.value.filter((item) => Number(item.project) === Number(targetForm.project)).map((item) => ({ label: `${item.name} · ${item.host}`, value: item.id })));
  const serviceServerOptions = computed(() => servers.value.filter((item) => Number(item.project) === Number(serviceForm.project)).map((item) => ({ label: `${item.name} · ${item.host}`, value: item.id })));
  const clusterPrometheusOptions = computed(() => prometheus.value.filter((item) => Number(item.project) === Number(clusterForm.project)).map((item) => ({ label: item.name, value: item.id })));
  const clusterServerOptions = computed(() => servers.value.filter((item) => Number(item.project) === Number(clusterForm.project)).map((item) => ({ label: `${item.name} · ${item.host}`, value: item.id })));
  const asList = <T,>(payload: unknown): T[] => {
    if (Array.isArray(payload)) return payload as T[];
    const response = payload as { list?: T[]; results?: T[]; data?: T[] } | null;
    return response?.list || response?.results || response?.data || [];
  };
  const load = async () => {
    if (!canMaintain.value) return;
    loading.value = true;
    const [prometheusResult, targetResult, serviceResult, serverResult] = await Promise.allSettled([
      MonitorAPI.prometheusList(selectedProject.value),
      MonitorAPI.targetList(selectedProject.value),
      MonitorAPI.serviceList(selectedProject.value),
      ServerConnectionAPI.list(selectedProject.value),
    ]);
    if (prometheusResult.status === 'fulfilled') prometheus.value = asList<PrometheusInstance>(prometheusResult.value);
    else message.error('Prometheus 实例加载失败');
    if (targetResult.status === 'fulfilled') targets.value = asList<MonitorTarget>(targetResult.value).filter((item) => item.project != null && managedProjectIds.value.has(Number(item.project)));
    else message.error('监控目标加载失败');
    if (serviceResult.status === 'fulfilled') services.value = asList<ServiceMonitor>(serviceResult.value).filter((item) => item.project != null && managedProjectIds.value.has(Number(item.project)));
    else message.error('服务监控加载失败');
    if (serverResult.status === 'fulfilled') servers.value = asList(serverResult.value);
    else servers.value = [];
    try { clusters.value = asList<MonitorCluster>(await MonitorAPI.clusterList(selectedProject.value)); } catch { clusters.value = []; message.error('集群加载失败'); }
    loading.value = false;
  };
  const openPrometheus = (row?: PrometheusInstance) => { editingPrometheus.value = row; Object.assign(prometheusForm, emptyPrometheus(), row ? { ...row, project: row.project == null ? null : Number(row.project), access_token: '' } : {}); prometheusVisible.value = true; };
  const openCluster = (row?: MonitorCluster) => { editingCluster.value = row; Object.assign(clusterForm, emptyCluster(), row || {}); clusterForm.project = row?.project == null ? selectedProject.value : Number(row.project); clusterForm.prometheus = row?.prometheus == null ? null : Number(row.prometheus); clusterForm.server = row?.server == null ? null : Number(row.server); clusterLabelsText.value = Object.entries(clusterForm.label_rules || {}).map(([key, value]) => `${key}=${value}`).join('\n'); clusterVisible.value = true; };
  const onClusterProjectChange = () => { clusterForm.prometheus = null; clusterForm.server = null; };
  const saveCluster = async () => { try { clusterForm.label_rules = Object.fromEntries(clusterLabelsText.value.split('\n').map((line) => line.trim()).filter((line) => line.includes('=')).map((line) => { const i = line.indexOf('='); return [line.slice(0, i).trim(), line.slice(i + 1).trim()]; })); if (!clusterForm.project || !clusterForm.prometheus || !clusterForm.name) return message.warning('请选择项目、Prometheus 并填写集群名称'); if (editingCluster.value?.id) await MonitorAPI.updateCluster(editingCluster.value.id, { ...clusterForm }); else await MonitorAPI.createCluster({ ...clusterForm }); clusterVisible.value = false; message.success('集群配置已保存'); await load(); } catch (error: any) { message.error(error?.message || '保存失败'); } };
  const syncCluster = async (row: MonitorCluster) => { try { const result = await MonitorAPI.syncCluster(row.id!); message.success(`同步完成：匹配 ${result.matched}，新增 ${result.created}，更新 ${result.updated}，离线 ${result.offline}`); await load(); } catch (error: any) { message.error(error?.message || '同步失败'); } };
  const removeCluster = async (row: MonitorCluster) => { try { await MonitorAPI.deleteCluster(row.id!); clusters.value = clusters.value.filter((item) => item.id !== row.id); targets.value = targets.value.filter((item) => item.cluster !== row.id); message.success('已删除'); } catch (error: any) { message.error(error?.message || '删除失败'); } };
  const openTarget = (row?: MonitorTarget) => {
    editingTarget.value = row;
    Object.assign(targetForm, emptyTarget(), row || {});
    targetForm.project = row?.project === null || row?.project === undefined ? null : Number(row.project);
    targetForm.prometheus = row?.prometheus === null || row?.prometheus === undefined ? null : Number(row.prometheus);
    targetForm.server = row?.server === null || row?.server === undefined ? null : Number(row.server);
    targetVisible.value = true;
  };
  const openService = (row?: ServiceMonitor) => { editingService.value = row; Object.assign(serviceForm, emptyService(), row || {}); serviceForm.project = row?.project == null ? null : Number(row.project); serviceForm.server = row?.server == null ? null : Number(row.server); serviceVisible.value = true; };
  const onTargetProjectChange = () => { targetForm.prometheus = null; targetForm.server = null; };
  const onServiceProjectChange = () => { serviceForm.server = null; };
  const savePrometheus = async () => { try { if (!prometheusForm.project || !prometheusForm.name || !prometheusForm.base_url) return message.warning('请选择所属项目并填写名称和 Prometheus 地址'); if (editingPrometheus.value?.id) await MonitorAPI.updatePrometheus(editingPrometheus.value.id, { ...prometheusForm }); else await MonitorAPI.createPrometheus({ ...prometheusForm }); prometheusVisible.value = false; message.success('Prometheus 已保存'); await load(); } catch (error: any) { message.error(error?.message || '保存失败'); } };
  const saveTarget = async () => { try { if (!targetForm.project || !targetForm.name || !targetForm.prometheus || !targetForm.instance_label) return message.warning('请选择所属项目并填写目标名称、Prometheus 实例和 Instance 标签'); if (editingTarget.value?.id) await MonitorAPI.updateTarget(editingTarget.value.id, { ...targetForm }); else await MonitorAPI.createTarget({ ...targetForm }); targetVisible.value = false; message.success('监控目标已保存'); await load(); } catch (error: any) { message.error(error?.message || '保存失败'); } };
  const saveService = async () => { try { if (!serviceForm.project || !serviceForm.name || !serviceForm.address) return message.warning('请选择所属项目并填写服务名称和服务地址'); if (serviceForm.monitor_type === 'tcp' && !serviceForm.port) return message.warning('TCP 监控必须填写端口'); if (editingService.value?.id) await MonitorAPI.updateService(editingService.value.id, { ...serviceForm }); else await MonitorAPI.createService({ ...serviceForm }); serviceVisible.value = false; message.success('服务监控已保存'); await load(); } catch (error: any) { message.error(error?.message || '保存失败'); } };
  const testTarget = async () => { try { const data = await MonitorAPI.testTarget(editingTarget.value!.id!); message.success(`指标连接正常，CPU ${data.current.cpu ?? '-'}%`); } catch (error: any) { message.error(error?.message || '测试失败'); } };
  const testService = async () => { try { const data = await MonitorAPI.testService(editingService.value!.id!); message.success(`服务在线，${data.response_time_ms ?? '-'} ms`); } catch (error: any) { message.error(error?.message || '服务不可用'); } };
  const removePrometheus = async (row: PrometheusInstance) => { try { await MonitorAPI.deletePrometheus(row.id!); prometheus.value = prometheus.value.filter((item) => item.id !== row.id); clusters.value = clusters.value.filter((item) => item.prometheus !== row.id); targets.value = targets.value.filter((item) => item.prometheus !== row.id); message.success('已删除'); } catch (error: any) { message.error(error?.message || '删除失败'); } }; const removeTarget = async (row: MonitorTarget) => { try { await MonitorAPI.deleteTarget(row.id!); targets.value = targets.value.filter((item) => item.id !== row.id); message.success('已删除'); } catch (error: any) { message.error(error?.message || '删除失败'); } };
  const removeService = async (row: ServiceMonitor) => { try { await MonitorAPI.deleteService(row.id!); services.value = services.value.filter((item) => item.id !== row.id); message.success('已删除'); } catch (error: any) { message.error(error?.message || '删除失败'); } };
  const actions = (row: any, edit: () => void, remove: () => void) => h(NSpace, { size: 14, wrap: false }, { default: () => [h(NButton, { text: true, type: 'primary', onClick: edit }, { default: () => '编辑' }), h(NPopconfirm, { onPositiveClick: remove }, { trigger: () => h(NButton, { text: true, type: 'error' }, { default: () => '删除' }), default: () => `确认删除「${row.name}」？` })] });
  const prometheusColumns: any[] = [{ title: '名称', key: 'name' }, { title: '所属项目', key: 'project_name', render: (row: PrometheusInstance) => row.project_name || '-' }, { title: '地址', key: 'base_url' }, { title: '状态', key: 'enabled', render: (row: PrometheusInstance) => h(NTag, { type: row.enabled ? 'success' : 'default' }, { default: () => row.enabled ? '启用' : '停用' }) }, { title: '操作', key: 'actions', width: 170, render: (row: PrometheusInstance) => actions(row, () => openPrometheus(row), () => removePrometheus(row)) }];
  const clusterColumns: any[] = [{ title: '集群名称', key: 'name' }, { title: '项目', key: 'project_name' }, { title: '发现方式', key: 'discovery_type', render: (row: MonitorCluster) => discoveryOptions.find((item) => item.value === row.discovery_type)?.label || row.discovery_type }, { title: 'Job', key: 'job' }, { title: '节点数', key: 'target_count' }, { title: '同步状态', key: 'last_sync_status', render: (row: MonitorCluster) => h(NTag, { type: row.last_sync_status === 'success' ? 'success' : row.last_sync_status === 'failed' ? 'error' : 'default' }, { default: () => row.last_sync_status === 'success' ? '成功' : row.last_sync_status === 'failed' ? '失败' : '未同步' }) }, { title: '操作', key: 'actions', width: 230, render: (row: MonitorCluster) => h(NSpace, { size: 14, wrap: false }, { default: () => [h(NButton, { text: true, type: 'primary', onClick: () => syncCluster(row) }, { default: () => '同步' }), h(NButton, { text: true, type: 'primary', onClick: () => openCluster(row) }, { default: () => '编辑' }), h(NPopconfirm, { onPositiveClick: () => removeCluster(row) }, { trigger: () => h(NButton, { text: true, type: 'error' }, { default: () => '删除' }), default: () => `确认删除「${row.name}」？` })] }) }];
  const targetColumns: any[] = [{ title: '目标名称', key: 'name' }, { title: '项目', key: 'project_name', render: (row: MonitorTarget) => row.project_name || '平台级' }, { title: '实例', key: 'instance_label' }, { title: 'Prometheus', key: 'prometheus_name' }, { title: '状态', key: 'enabled', render: (row: MonitorTarget) => h(NTag, { type: row.enabled ? 'success' : 'default' }, { default: () => row.enabled ? '启用' : '停用' }) }, { title: '操作', key: 'actions', width: 170, render: (row: MonitorTarget) => actions(row, () => openTarget(row), () => removeTarget(row)) }];
  const serviceColumns: any[] = [{ title: '服务名称', key: 'name' }, { title: '项目', key: 'project_name', render: (row: ServiceMonitor) => row.project_name || '平台级' }, { title: '类型', key: 'monitor_type', render: (row: ServiceMonitor) => row.monitor_type.toUpperCase() }, { title: '地址', key: 'address' }, { title: '状态', key: 'enabled', render: (row: ServiceMonitor) => h(NTag, { type: row.enabled ? 'success' : 'default' }, { default: () => row.enabled ? '启用' : '停用' }) }, { title: '操作', key: 'actions', width: 170, render: (row: ServiceMonitor) => actions(row, () => openService(row), () => removeService(row)) }];
  const loadProjects = async () => {
    try {
      const response: any = await http.request({ url: '/project/project/', method: 'get', params: { page: 1, pageSize: 1000 } });
      projects.value = asList(response);
    } catch (error: any) {
      projects.value = [];
      message.error(error?.message || '项目列表加载失败');
    } finally { projectsLoaded.value = true; }
  };
  onMounted(async () => { await loadProjects(); await load(); });
</script>

<style scoped lang="less">.access-denied { display:flex; min-height:calc(100vh - 150px); flex-direction:column; justify-content:center; padding:24px; box-sizing:border-box; }.monitor-config { padding: 24px 28px; }.monitor-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 20px; }.monitor-header h2 { margin: 0; color: #1e293b; }.monitor-header p { margin: 8px 0 22px; color: #7b8ba3; }.header-actions { display: flex; align-items: center; gap: 12px; }.project-filter { width: 200px; }.toolbar { display: flex; justify-content: flex-end; margin-bottom: 14px; }.target-form-tip { margin-bottom: 16px; }.threshold-title { margin: 8px 0 4px; color: #34435a; font-weight: 600; }.threshold-inputs { display: grid; grid-template-columns: 1fr 1fr; width: 100%; gap: 8px; }</style>
