<template>
  <section class="app-page">
    <header class="page-header"><div><h2>设备管理</h2><p>维护 Appium 执行节点和 Android 真机、模拟器。</p></div></header>
    <n-tabs v-model:value="tab" type="line">
      <n-tab-pane name="device" tab="设备"><div class="toolbar"><n-select v-model:value="project" clearable :options="projectOptions" placeholder="全部项目" /><n-button @click="load">刷新</n-button><n-button type="primary" @click="openDevice()">新增设备</n-button></div><n-data-table :loading="loading" :columns="deviceColumns" :data="devices" :row-key="(r)=>r.id" /></n-tab-pane>
      <n-tab-pane name="node" tab="执行节点"><div class="toolbar"><n-select v-model:value="project" clearable :options="projectOptions" placeholder="全部项目" /><n-button @click="load">刷新</n-button><n-button type="primary" @click="openNode()">新增节点</n-button></div><n-data-table :loading="loading" :columns="nodeColumns" :data="nodes" :row-key="(r)=>r.id" /></n-tab-pane>
    </n-tabs>
    <n-modal v-model:show="showNode" preset="card" :title="nodeForm.id?'编辑执行节点':'新增执行节点'" class="platform-form-modal app-modal"><n-form label-placement="top"><n-form-item label="所属项目"><n-select v-model:value="nodeForm.project" :options="projectOptions" /></n-form-item><n-form-item label="节点名称"><n-input v-model:value="nodeForm.name" /></n-form-item><n-form-item label="Appium 地址"><n-input v-model:value="nodeForm.server_url" placeholder="http://127.0.0.1:4723" /></n-form-item><n-form-item><n-switch v-model:value="nodeForm.enabled" />启用</n-form-item></n-form><template #footer><n-space justify="end"><n-button @click="showNode=false">取消</n-button><n-button type="primary" @click="saveNode">保存</n-button></n-space></template></n-modal>
    <n-modal v-model:show="showDevice" preset="card" :title="deviceForm.id?'编辑设备':'新增设备'" class="platform-form-modal app-modal"><n-form label-placement="top"><div class="form-grid"><n-form-item label="所属项目"><n-select v-model:value="deviceForm.project" :options="projectOptions" @update:value="deviceForm.node=null" /></n-form-item><n-form-item label="执行节点"><n-select v-model:value="deviceForm.node" :options="availableNodes" /></n-form-item><n-form-item label="设备名称"><n-input v-model:value="deviceForm.name" /></n-form-item><n-form-item label="ADB Device ID"><n-input v-model:value="deviceForm.udid" /></n-form-item></div><n-form-item><n-switch v-model:value="deviceForm.enabled" />启用</n-form-item></n-form><template #footer><n-space justify="end"><n-button @click="showDevice=false">取消</n-button><n-button type="primary" @click="saveDevice">保存</n-button></n-space></template></n-modal>
  </section>
</template>
<script setup lang="ts">
import { asList } from '@/utils/list';

import { computed,h,onMounted,reactive,ref } from 'vue';
import { NButton,NSpace,NTag,useDialog,useMessage } from 'naive-ui';
import { ProjectAPI } from '@/api/project/http';
import { AppTestAPI,type AppDevice,type AppExecutionNode } from '@/api/case_app/http';
const message=useMessage(),dialog=useDialog(),projectApi=new ProjectAPI(),loading=ref(false),tab=ref('device'),project=ref<number|null>(null),projects=ref<any[]>([]),nodes=ref<AppExecutionNode[]>([]),devices=ref<AppDevice[]>([]),showNode=ref(false),showDevice=ref(false);
const projectOptions=computed(()=>projects.value.map(p=>({label:p.name,value:Number(p.id)})));const availableNodes=computed(()=>nodes.value.filter(n=>!deviceForm.project||n.project===deviceForm.project).map(n=>({label:n.name,value:Number(n.id)})));
const emptyNode=():AppExecutionNode=>({project:null,name:'',server_url:'http://127.0.0.1:4723',enabled:true});const nodeForm=reactive<AppExecutionNode>(emptyNode());const emptyDevice=():AppDevice=>({project:null,node:null,name:'',udid:'',platform:'android',platform_version:'',model:'',resolution:'',enabled:true});const deviceForm=reactive<AppDevice>(emptyDevice());
const stateMap:any={unknown:['未知','default'],online:['在线','success'],offline:['离线','error'],busy:['占用中','warning'],inspecting:['检查中','info']};
const formatResolution=(value:unknown)=>{const resolution=String(value||'').trim();if(!resolution)return '-';const match=resolution.match(/^(\d+)\s*[xX×*]\s*(\d+)$/);return match?`${match[1]} × ${match[2]}`:resolution;};
const nodeColumns:any[]=[{title:'节点名称',key:'name'},{title:'所属项目',key:'project_name'},{title:'Appium 地址',key:'server_url'},{title:'设备数',key:'device_count',width:80},{title:'状态',key:'status',width:90,render:(r:any)=>h(NTag,{type:stateMap[r.status]?.[1]||'default'},{default:()=>stateMap[r.status]?.[0]||r.status})},{title:'最近信息',key:'last_message',ellipsis:{tooltip:true}},{title:'操作',key:'action',width:220,render:(r:any)=>h(NSpace,{size:12,wrap:false},{default:()=>[h(NButton,{text:true,type:'primary',onClick:()=>testNode(r)},{default:()=> '测试连接'}),h(NButton,{text:true,type:'primary',onClick:()=>openNode(r)},{default:()=> '编辑'}),h(NButton,{text:true,type:'error',onClick:()=>removeNode(r)},{default:()=> '删除'})]})}];
const deviceColumns:any[]=[{title:'设备名称',key:'name'},{title:'所属项目',key:'project_name'},{title:'执行节点',key:'node_name'},{title:'Device ID',key:'udid'},{title:'型号/系统',key:'model',render:(r:any)=>`${r.model||'-'} / ${r.platform_version||'-'}`},{title:'分辨率',key:'resolution',width:132,render:(r:any)=>h('span',{class:'resolution-value'},formatResolution(r.resolution))},{title:'状态',key:'state',width:90,render:(r:any)=>h(NTag,{type:stateMap[r.state]?.[1]||'default'},{default:()=>stateMap[r.state]?.[0]||r.state})},{title:'操作',key:'action',width:220,render:(r:any)=>h(NSpace,{size:12,wrap:false},{default:()=>[h(NButton,{text:true,type:'primary',loading:r.__testing,onClick:()=>testDevice(r)},{default:()=> '测试连接'}),h(NButton,{text:true,type:'primary',onClick:()=>openDevice(r)},{default:()=> '编辑'}),h(NButton,{text:true,type:'error',onClick:()=>removeDevice(r)},{default:()=> '删除'})]})}];
async function load(){loading.value=true;try{const [n,d]=await Promise.all([AppTestAPI.nodes({project:project.value||undefined,pageSize:1000}),AppTestAPI.devices({project:project.value||undefined,pageSize:1000})]);nodes.value=asList(n);devices.value=asList(d);}finally{loading.value=false;}}
function openNode(row?:AppExecutionNode){Object.assign(nodeForm,emptyNode(),row||{});showNode.value=true;}function openDevice(row?:AppDevice){Object.assign(deviceForm,emptyDevice(),row||{});showDevice.value=true;}
async function saveNode(){if(!nodeForm.project||!nodeForm.name||!nodeForm.server_url)return message.warning('请填写完整节点信息');await AppTestAPI.saveNode({...nodeForm});showNode.value=false;message.success('保存成功');await load();}
async function saveDevice(){if(!deviceForm.project||!deviceForm.node||!deviceForm.name||!deviceForm.udid)return message.warning('请填写完整设备信息');await AppTestAPI.saveDevice({...deviceForm});showDevice.value=false;message.success('保存成功');await load();}
async function testNode(row:any){try{await AppTestAPI.testNode(row.id);message.success('Appium 节点连接成功');}catch(e:any){message.error(e?.message||'节点连接失败');}await load();}async function testDevice(row:any){row.__testing=true;try{await AppTestAPI.testDevice(row.id);message.success('设备连接成功');}catch(e:any){message.error(e?.message||'设备连接失败');}finally{row.__testing=false;}await load();}
function removeNode(row:any){dialog.warning({title:'删除节点',content:`确定删除「${row.name}」吗？`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{await AppTestAPI.deleteNode(row.id);await load();}})}function removeDevice(row:any){dialog.warning({title:'删除设备',content:`确定删除「${row.name}」吗？`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{await AppTestAPI.deleteDevice(row.id);await load();}})}
onMounted(async()=>{projects.value=asList(await projectApi.getDataList({pageSize:1000}));await load();});
</script>
<style scoped lang="less">.app-page{padding:24px 28px}.page-header h2{margin:0;color:#1e293b}.page-header p{margin:8px 0 20px;color:#7b8ba3}.toolbar{display:flex;justify-content:flex-end;gap:10px;margin-bottom:14px}.toolbar .n-select{width:220px}.resolution-value{display:inline-block;color:#334155;white-space:nowrap;font-variant-numeric:tabular-nums}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:0 16px}@media(max-width:640px){.app-page{padding:16px}.toolbar,.form-grid{grid-template-columns:1fr;display:grid}.toolbar .n-select{width:100%}}</style>
