<template><section class="app-page"><header class="page-header"><div><h2>执行任务</h2><p>查看 App 自动化任务状态、设备占用和执行结果。</p></div><n-button @click="load">刷新</n-button></header><div class="filters"><n-select v-model:value="project" clearable :options="projectOptions" placeholder="全部项目"/><n-select v-model:value="status" clearable :options="statusOptions" placeholder="全部状态"/><n-button @click="load">查询</n-button></div><n-data-table :loading="loading" :columns="columns" :data="rows" :row-key="r=>r.id"/></section></template>
<script setup lang="ts">
import { usePolling } from '@/hooks/web/usePolling';
import { appStatusLabels as labels, isAppActive as active } from '@/utils/executionStatus';

import { asList } from '@/utils/list';
import{computed,h,onMounted,ref}from'vue';import{NButton,NProgress,NSpace,NTag,useDialog,useMessage}from'naive-ui';import{useRouter}from'vue-router';import{ProjectAPI}from'@/api/project/http';import{AppTestAPI,type AppRun}from'@/api/case_app/http';
const router=useRouter(),message=useMessage(),dialog=useDialog(),projectApi=new ProjectAPI(),rows=ref<AppRun[]>([]),projects=ref<any[]>([]),loading=ref(false),project=ref<number|null>(null),status=ref<string|null>(null);const poller = usePolling();const projectOptions=computed(()=>projects.value.map(p=>({label:p.name,value:Number(p.id)})));const statusOptions=Object.entries(labels).map(([value,item]:any)=>({value,label:item[0]}));
const progressColor=(s:string)=>s==='passed'?'#18a36b':s==='failed'||s==='error'?'#dc4c55':s==='stopped'?'#94a3b8':'#2f7ee6';
const columns:any[]=[{title:'执行编号',key:'execution_no',width:130},{title:'App 用例',key:'case_name'},{title:'所属项目',key:'project_name'},{title:'应用',key:'application_name'},{title:'设备',key:'device_name'},{title:'状态',key:'status',width:100,render:(r:any)=>h(NTag,{type:labels[r.status]?.[1]||'default'},{default:()=>labels[r.status]?.[0]||r.status})},{title:'进度',key:'progress',width:180,render:(r:any)=>{const percentage=Math.max(0,Math.min(100,Math.round(Number(r.progress)||0)));return h('div',{class:'app-task-progress'},[h(NProgress,{class:'app-task-progress__bar',type:'line',percentage,height:7,borderRadius:4,showIndicator:false,color:progressColor(r.status),railColor:'#e7edf4'}),h('span',{class:['app-task-progress__value',`is-${r.status}`]},`${percentage}%`)])}},{title:'开始时间',key:'started_at',width:170,render:(r:any)=>r.started_at?new Date(r.started_at).toLocaleString():'-'},{title:'操作',key:'action',width:180,render:(r:any)=>h(NSpace,{size:12,wrap:false},{default:()=>[h(NButton,{text:true,type:'primary',onClick:()=>router.push({name:'execution_report',params:{sourceType:'app',id:r.id}})},{default:()=> '查看报告'}),active(r.status)?h(NButton,{text:true,type:'error',onClick:()=>stop(r)},{default:()=> '停止'}):h(NButton,{text:true,type:'error',onClick:()=>remove(r)},{default:()=> '删除'})]})}];
async function load(){loading.value=true;try{rows.value=asList(await AppTestAPI.runs({project:project.value||undefined,status:status.value||undefined,pageSize:1000,_t:Date.now()}));}finally{loading.value=false;}}async function stop(r:AppRun){await AppTestAPI.stop(r.id);message.success('已发送停止指令');await load();}function remove(r:AppRun){dialog.warning({title:'删除执行任务',content:`确定删除「${r.execution_no}」及其报告附件吗？`,positiveText:'删除',negativeText:'取消',onPositiveClick:async()=>{await AppTestAPI.deleteRun(r.id);await load();}})}onMounted(async()=>{projects.value=asList(await projectApi.getDataList({pageSize:1000}));await load();poller.start(()=>{if(rows.value.some(r=>active(r.status)))void load();},3000)});</script>
<style scoped lang="less">.app-page{padding:24px 28px}.page-header{display:flex;justify-content:space-between;gap:16px}.page-header h2{margin:0}.page-header p{margin:8px 0 22px;color:#7b8ba3}.filters{display:grid;grid-template-columns:220px 180px max-content;gap:12px;margin-bottom:16px}.app-task-progress{display:flex;align-items:center;gap:10px;width:100%;min-width:0}.app-task-progress__bar{min-width:78px;flex:1}.app-task-progress__value{flex:0 0 40px;color:#475569;font-size:13px;font-weight:650;line-height:1;text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums}.app-task-progress__value.is-passed{color:#128158}.app-task-progress__value.is-failed,.app-task-progress__value.is-error{color:#c53c47}.app-task-progress__value.is-stopped{color:#7b8797}@media(max-width:640px){.app-page{padding:16px}.page-header{flex-direction:column}.filters{grid-template-columns:1fr}}</style>
